- name: pytorch
  title: PyTorch nightly builds compromised via malicious dependency
  repo: https://github.com/pytorch/pytorch
  synopsis: PyTorch nightly builds were compromised when a malicious package named `torchtriton` was uploaded to PyPI. The PyTorch build process imported this package due to dependency confusion. The malicious `torchtriton` exfiltrated sensitive information from the build environment and executed code.
  start_date: 2022-12-25
  end_date: 2022-12-30
  attribution_type: Individual hacker
  component_type: Library # Machine Learning Framework
  lang: Python
  cause: Dependency confusion
  motive: Data theft, Remote execution
  transitive: true # Malicious code was in the dependency
  insertion_phase: dependency # Build system pulled malicious dependency from PyPI
  impact_type: Data theft, Credential theft, Remote execution
  references:
    - https://pytorch.org/blog/security-alert/
    - https://blog.checkpoint.com/research/supply-chain-attack-on-pytorch-dependency-confusion-via-malicious-packages/
    - https://blog.sonatype.com/pytorch-hijacked-dependency-confusion-2.0
  versions:
    - Nightly builds between 2022-12-25 and 2022-12-30
  historical_artifacts:
    - https://pypi.org/project/torchtriton/2.0.0.post1/
    - https://pypi.org/simple/torchtriton/
  current_artifacts:
    - https://pytorch.org/blog/security-alert/ # Official advisory with technical details
    - https://blog.checkpoint.com/research/supply-chain-attack-on-pytorch-dependency-confusion-via-malicious-packages/ # Analysis with screenshots
  domain: pypi.org
  domain_type: package host
  artifact_type: source archive
  hashes:
    - sha256:919118939367690c239923b9748520c261503865094823459177886619378916 # torchtriton-2.0.0.post1.tar.gz
  clean: true