- name: vsftpd
  title: vsftpd official distribution site compromised distributing backdoor
  synopsis: The FTP server hosting the official vsftpd source code tarballs was compromised. For a brief period, the download for vsftpd version 2.3.4 was replaced with a version containing a backdoor. This backdoor opened a listening shell on TCP port 6200 when a username ending in ':)' was used to log in.
  start_date: 2011-07-03 # Approximate date/time of compromise
  end_date: 2011-07-03 # Discovered and removed very quickly
  attribution_type: Individual hacker
  component_type: Application # FTP Server
  lang: C # Backdoor code in C source
  cause: Server compromise # Master distribution site hacked
  motive: Remote access # Listening shell
  insertion_phase: distribution # Official download source tarball replaced
  impact_type: Backdoor, Remote execution
  references:
    - https://scarybeastsecurity.blogspot.com/2011/07/alert-vsftpd-download-backdoored.html # Author's blog post
    - https://www.rapid7.com/db/modules/exploit/unix/ftp/vsftpd_234_backdoor/ # Exploit module details
    - https://www.computerworld.com/article/2518230/vsftpd-developer-confirms-backdoor-in-version-2-3-4.html # News report
  versions:
    - 2.3.4 # Specific source tarball vsftpd-2.3.4.tar.gz
  impacted_hashes:
    # Hashes difficult to confirm as file was removed quickly
