- name: Classic Shell
  title: Classic Shell compromised on FossHub
  repo: https://github.com/coddec/Classic-Shell
  synopsis: The FossHub distribution platform was compromised, and downloads for Classic Shell were replaced with a destructive application. The malicious installer would rewrite the master boot record causing boot failures.
  start_date: 2016-08-02
  end_date: 2016-08-03
  attribution_type: Individual Hacker
  component_type: Application
  lang: C++
  cause: Compromised Infrastructure
  motive: Disruption/Protest
  transitive: false
  historical_artifacts:
    - https://www.fosshub.com/Classic-Shell.html # Original distribution site (compromised version)
  current_artifacts:
    - https://www.bleepingcomputer.com/news/security/classicshell-and-fosshub-hacked-mbr-wiper-installed-instead-of-app/ # Analysis with MBR wiper details
    - https://github.com/hfiref0x/Misc/tree/master/FossHub%20Malware%20Aug%202016 # Sample of the malicious code
  insertion_phase: distribution
  impact_type: Service Disruption/Data Destruction
  impact_user_count: 10000
  references:
    - https://www.ghacks.net/2016/08/03/attention-fosshub-downloads-compromised/
    - https://web.archive.org/web/20160803032356/http://www.classicshell.net/forum/viewtopic.php?f=12&t=6434 # Original Classic Shell forum report (archived)
    - https://www.bleepingcomputer.com/news/security/classicshell-and-fosshub-hacked-mbr-wiper-installed-instead-of-app/
    - https://thehackernews.com/2016/08/FossHub-malware.html
    - https://arstechnica.com/information-technology/2016/08/malicious-classic-shell-installer-deliberately-trashes-windows-pcs/ # News report detailing the MBR wiper and FossHub's response
  domain: fosshub.com
  domain_type: package host
  artifact_type: binary archive
  hashes:
    - sha256:ccbb6cd10c0b0cfb68cf7c4203c9e9b75eb28b9a69a639e2c11a69d623456fa7 # Malicious installer hash
    - md5:55a76272c2e42285ad4414e328b88e16 # Alternative hash for malicious installer
