- name: Sky Villages [Forge/Fabric]
  title: Sky Villages mod compromised with Fracturiser malware
  synopsis: The CurseForge account associated with the 'Sky Villages' Minecraft mod was compromised. Attackers uploaded a malicious JAR file appearing as a legitimate update for the mod. This file contained the 'Fracturiser' malware, which steals various credentials and attempts to infect other JAR files on the victim's computer.
  start_date: 2023-05-01 # Approximate timeframe malicious files started appearing for various mods
  end_date: 2023-06-08 # Approximate date of widespread discovery and public warnings
  attribution_type: Unknown # Attacker(s) compromising accounts
  component_type: Game mod # Minecraft Java Edition Mod
  lang: Java
  cause: Stolen credentials # Compromised CurseForge/BukkitDev account
  motive: Credential theft, Malware propagation
  insertion_phase: distribution # Malicious JAR uploaded to official mod platform
  impact_type: Credential theft, Data theft, Malware infection
  domain: curseforge.com
  domain_type: package host
  artifact_type: binary archive
  historical_artifacts:
    - https://www.curseforge.com/minecraft/mc-mods/sky-villages-forge-fabric # Original hosting location for the compromised mod
  current_artifacts:
    - https://github.com/fractureiser-investigation/fractureiser # GitHub repository with samples and analysis
    - https://securelist.com/fracturiser-supply-chain-attack-infecting-minecraft-mods/110014/ # Analysis with technical details
  hashes:
    - sha256:5584ac1f8b713d2f6310bd3cde425b775402fbc70e56e5e8d774bec15703ca79 # Malicious JAR hash related to Fracturiser campaign
  references:
    - https://support.curseforge.com/en/support/solutions/articles/9000228509-june-2023-infected-mods-detection-tool-and-report # CurseForge Advisory listing affected projects
    - https://securelist.com/fracturiser-supply-chain-attack-infecting-minecraft-mods/110014/ # Technical analysis
  versions: # Specific versions varied, updates pushed around May/June 2023 were affected
