- name: Inbenta
  title: Inbenta chatbot script compromised, hit Ticketmaster.
  synopsis: A third-party chatbot script provided by Inbenta Technologies to Ticketmaster UK (and potentially others) was compromised by attackers (Magecart group). Malicious JavaScript skimming code was injected into the legitimate script, allowing theft of payment card details and PII from users on Ticketmaster's payment pages where the widget was active.
  start_date: 2018-02-10 # Approximate start date of compromise/activity based on reports
  end_date: 2018-06-23 # Date Ticketmaster identified and disabled the compromised script
  attribution_type: Cybercriminal group # Magecart
  component_type: library # Third-party JavaScript widget/service
  cause: Vendor compromise # Inbenta's script/service compromised (exact vector unclear)
  motive: Financial gain # Credit card and PII theft
  transitive: false
  insertion_phase: distribution # Compromised script served by vendor/deployed by client
  impact_type: Skimming, Data theft, Credential theft
  impact_user_count: 40000 # Estimated Ticketmaster UK customers affected (<5% of global base)
  references:
    - https://www.wired.co.uk/article/ticketmaster-hack-inbenta-security-breach
    - https://thehackernews.com/2018/06/ticketmaster-data-breach.html
    - https://www.bankinfosecurity.com/ticketmaster-fined-17-million-for-data-security-failures-a-15369 # Discusses ICO fine and Inbenta role
    - https://datadome.co/learning-center/magecart-attacks/ # Cites Ticketmaster/Inbenta case
  versions:
    - "Specific customized JavaScript provided by Inbenta to Ticketmaster, active Feb-June 2018"
  artifacts:
    - "Compromised Inbenta JavaScript file loaded on Ticketmaster payment pages"
  domain: Inbenta Technologies # Vendor whose supplied script was compromised
  domain_type: project host # Service provider
  artifact_type: source archive # JavaScript file/service
