- name: MeDoc
  title: MeDoc updates distributed NotPetya ransomware.
  synopsis: The update mechanism for MeDoc, a popular Ukrainian accounting software, was compromised. Attackers used it to distribute the NotPetya malware, which initially masqueraded as ransomware but functioned primarily as a destructive wiper, causing global disruption.
  start_date: 2017-04-01 # Approximate date backdoor was first installed on MeDoc servers (some evidence suggests April 2017)
  end_date: 2017-06-27 # Date of the main NotPetya outbreak via MeDoc
  attribution_type: Nation-state
  component_type: application # Accounting software
  cause: build server compromise
  motive: Data destruction, Disruption, Espionage (initial backdoor)
  transitive: false
  insertion_phase: distribution # Malicious payload pushed via software update server
  impact_type: Ransomware (wiper), Data destruction, Denial of service
  impact_user_count: 400000 # Estimated MeDoc customer base in Ukraine; global impact far wider
  references:
    - https://www.wired.com/story/notpetya-cyberattack-ukraine-russia-code-crashed-the-world/
    - https://www.us-cert.gov/ncas/alerts/TA17-181A
    - https://www.welivesecurity.com/2017/07/04/connection-telebots-past-attacks-current-medoc-situation/
  versions:
    - "Specific MeDoc update versions distributed on or around June 27, 2017" # Exact version numbers of MeDoc updates often not cited, but the update mechanism was the vector
  domain: medoc.ua # Original software vendor domain
  domain_type: project host
  artifact_type: binary archive
  historical_artifacts:
    - "MeDoc software updates distributed via medoc.ua's update server (e.g., upd.me-doc.com.ua) around June 27, 2017."
  current_artifacts:
    - "https://www.welivesecurity.com/2017/06/30/telebots-back-supply-chain-attacks-against-ukraine/" # ESET analysis of the initial backdoor and NotPetya
    - "https://www.microsoft.com/en-us/security/blog/2017/06/27/new-ransomware-old-techniques-petya-outbreak-originates-in-ukraine-spreads-globally/" # Microsoft analysis
    - "https://www.virustotal.com/gui/file/027cc450ef5f8c5f653329641ec1fed91f694e0d229928963b30f6b0d7d3a745" # NotPetya main DLL (perfc.dat)
    - "https://www.virustotal.com/gui/file/13d5006285b3f9151e7e7f98e75a99534a831510f6e6d4f1a24713004f014906" # MeDoc EzVit.exe compromised updater
  hashes:
    - sha256:027cc450ef5f8c5f653329641ec1fed91f694e0d229928963b30f6b0d7d3a745 # NotPetya DLL (often named perfc.dat or similar)
    - sha256:13d5006285b3f9151e7e7f98e75a99534a831510f6e6d4f1a24713004f014906 # MeDoc EzVit.exe (compromised updater component)
    - md5:71b6a493388e7d0b40c83ce903bc6b04 # NotPetya DLL
