- name: phpmyadmin
  title: phpMyAdmin SourceForge mirror distributes JavaScript malware (2009)
  repo: https://github.com/phpmyadmin/phpmyadmin
  synopsis: Downloads of phpMyAdmin obtained from certain compromised SourceForge mirrors contained injected malicious JavaScript code within legitimate files (like js/cross_framing_protection.js). When an administrator used the compromised phpMyAdmin installation, this JavaScript executed in their browser, potentially redirecting them or loading external malicious content. This was separate from a later backdoor incident in 2012.
  start_date: 2008-12-01 # Approximate date modified packages started appearing based on reports
  end_date: 2009-01-21 # Date phpMyAdmin formally warned users (PMASA-2009-1)
  attribution_type: Cybercriminal gang # Likely based on motive
  component_type: Application # Database management tool
  lang: Javascript
  cause: Server compromise # SourceForge mirror infrastructure
  motive: Malware distribution # Or phishing/traffic theft
  transitive: false
  insertion_phase: distribution # Compromise of official download mirror network
  impact_type: Malware distribution, Browser compromise
  references:
    - https://web.archive.org/web/20090202060440/http://www.phpmyadmin.net/home_page/security.php?issue=PMASA-2009-1 # Archived official security announcement (PMASA-2009-1)
    - https://www.securityfocus.com/bid/33200 # SecurityFocus entry for the issue
  versions:
    - 3.1.1 # Downloads corresponding to this version were affected, potentially others around this timeframe
  historical_artifacts:
    - https://sourceforge.net/projects/phpmyadmin/files/phpMyAdmin/3.1.1/phpMyAdmin-3.1.1-all-languages.zip/download # Original download URL from compromised mirror
    - http://jaist.dl.sourceforge.net/project/phpmyadmin/phpMyAdmin/3.1.1/phpMyAdmin-3.1.1-all-languages.zip # Specific mirror URL potentially affected
  current_artifacts:
    - https://web.archive.org/web/20090202060440/http://www.phpmyadmin.net/home_page/security.php?issue=PMASA-2009-1 # Archived advisory with technical details
    - https://www.securityfocus.com/bid/33200 # Analysis with details of the JavaScript injection
  domain: sourceforge.net
  domain_type: package host
  artifact_type: source archive
  hashes:
    - md5:9537f4c5f9b959d24aad55ea0e4d9ebb # Potentially compromised phpMyAdmin-3.1.1-all-languages.zip
