- name: pear
  title: PEAR PHP installer go-pear.phar compromised on server
  synopsis: The official `go-pear.phar` installer file hosted on the `pear.php.net` server was compromised and replaced with a malicious version. Users downloading and executing this compromised installer could have had their systems backdoored. The compromise lasted approximately six months before discovery.
  start_date: 2018-06-20 # Estimated start based on file timestamp (may vary)
  end_date: 2019-01-19
  attribution_type: Unknown
  component_type: Library # Package manager/installer
  lang: PHP
  cause: Server compromise # pear.php.net server hacked
  motive: Unknown # Potential backdoor/further access
  insertion_phase: distribution # Official download file replaced
  impact_type: Potential backdoor, Remote execution
  references:
    - https://news-web.php.net/php.pear.cvs/11001 # Mailing list announcement
    - https://thehackernews.com/2019/01/php-pear-package-hack.html
    - https://www.zdnet.com/article/hacker-backdoors-php-pear-package-manager/
  artifacts:
    - url: http://pear.php.net/go-pear.phar # Original URL of the compromised file (now serves clean version)
  impacted_hashes:
    - 1e623a48b8991980e93896153651135ab7ab82a0 # SHA1 hash mentioned in announcements (SHA256 preferred but may not be available)
