- name: php
  title: PHP Git server compromise attempts source code backdoor
  synopsis: Attackers compromised the self-hosted `git.php.net` server. They pushed two malicious commits directly to the php-src repository ('main' branch). These commits attempted to insert a backdoor enabling remote code execution, disguised as typo fixes. The commits were detected quickly and did not impact any released version. PHP migrated to GitHub afterwards.
  start_date: 2021-03-28
  end_date: 2021-03-28
  attribution_type: Unknown # Claimed to be Zerodium, but unconfirmed
  component_type: Library # Language runtime
  lang: C
  cause: Server compromise # Git server credentials/access compromised
  motive: Espionage # Remote code execution backdoor
  insertion_phase: source # Direct commit to authoritative repository
  impact_type: Potential backdoor, Remote execution # If released
  references:
    - https://news-web.php.net/php.internals/113838 # Official announcement
    - https://www.bleepingcomputer.com/news/security/phps-git-server-hacked-to-add-backdoors-to-php-source-code/
    - https://github.com/php/php-src/issues/6900 # Discussion related to the incident
  commits:
    - c730aa26bd52829a49f2ad284b181b7e82a68d7d
    - 2b0f239b211c7544fcad542144ceca7d9b0ab58e # Malicious commits (reverted)
  artifacts:
    - url: https://github.com/php/php-src/commit/c730aa26bd52829a49f2ad284b181b7e82a68d7d
    - url: https://github.com/php/php-src/commit/2b0f239b211c7544fcad542144ceca7d9b0ab58e
