- name: handbrake
  title: HandBrake Mac download mirror distributed Proton RAT
  synopsis: An official HandBrake download mirror server (download.handbrake.fr) hosting the macOS version was compromised. The HandBrake-1.0.7.dmg file was replaced with a malicious version containing the Proton Remote Access Trojan (RAT). Users downloading the Mac version from this mirror were infected.
  start_date: 2017-05-02 # Approximate start of compromise window
  end_date: 2017-05-06
  attribution_type: Individual hacker # Or group distributing Proton RAT
  component_type: Application
  lang: Binary # Malware was embedded in DMG
  cause: Server compromise # Mirror server hacked
  motive: Credential theft # Proton RAT capabilities
  transitive: false
  insertion_phase: distribution # Compromise of official download mirror
  impact_type: Remote access, Credential theft
  references:
    - https://arstechnica.com/information-technology/2017/05/handbrake-download-server-hacked-to-distribute-mac-malware/ # Ars Technica article
    - https://securelist.com/proton-mac-os-x-rat/79960/ # Securelist (Kaspersky) analysis of Proton RAT, mentions HandBrake compromise
    - https://forum.handbrake.fr/viewtopic.php?f=33&t=36380 # Official announcement by HandBrake team
  versions:
    - 1.0.7 # Specific Mac DMG file
  historical_artifacts:
    - https://download.handbrake.fr/1.0.7/HandBrake-1.0.7.dmg # Original compromised download URL
    - https://mirror.download.handbrake.fr/1.0.7/HandBrake-1.0.7.dmg # Alternate mirror that may have been affected
  current_artifacts:
    - https://objective-see.org/blog/blog_0x1D.html # Analysis with screenshots and details
    - https://www.cybereason.com/blog/labs-proton-b-what-this-mac-malware-actually-does # Technical analysis of the Proton malware
  domain: download.handbrake.fr
  domain_type: project host
  artifact_type: binary archive
  hashes:
    - sha256:0935a43ca90c6c419a49e4f8f1d75e68cd70cb90b79306ce0cc7af2716aaa377 # Malicious HandBrake-1.0.7.dmg
    - sha1:32176407013738cb03959d0945993c13373f9590 # Malicious HandBrake-1.0.7.dmg
    - sha256:013623e5e50449bbdf6943549d8224a122aa6c42bd3300a1bd2b743b01ae6793 # Legitimate HandBrake-1.0.7.dmg
    - sha1:230a3e5404b633882b799d84633206b98e80790d # Legitimate HandBrake-1.0.7.dmg
  clean: true
