- name: FreeDownloadManager
  title: FreeDownloadManager site served backdoored Linux version.
  synopsis: The official FreeDownloadManager website was compromised, intermittently redirecting Linux users to a domain serving a trojanized Debian package. This package installed a backdoor and an information-stealing malware targeting passwords, crypto wallets, and cloud credentials.
  start_date: 2020-01-24 # Approximate start of malicious redirection and infected package availability
  end_date: 2022-01-01 # Approximate date the vulnerability was unknowingly resolved (incident active 2020-2022, disclosed Sept 2023)
  attribution_type: Cybercriminal group # Attributed by FDM to a "Ukrainian hacker group"
  component_type: application # Download manager utility
  cause: Website compromise # Specific webpage vulnerability exploited
  motive: Financial gain, Data theft
  transitive: false
  lang: shell
  insertion_phase: distribution # Compromised official download website leading to malicious package
  impact_type: Backdoor, Credential theft, Data theft
  impact_user_count: 10000 # Estimate, FDM stated <0.1% of visitors; actual infected count unknown but potentially significant over 3 years
  references:
    - https://securelist.com/backdoored-free-download-manager-linux-malware/110465/
    - https://thehackernews.com/2023/09/free-download-manager-site-compromised.html
    - https://www.bleepingcomputer.com/news/security/free-download-manager-website-hacked-to-spread-linux-malware/
    - https://www.freedownloadmanager.org/blog/fdm-vulnerability-disclosure/ # FDM's official statement (check for active link)
  versions:
    - "Specific Linux Debian packages distributed via malicious redirect from freedownloadmanager.org between 2020-2022"
  artifacts:
    - "freedownloadmanager.deb" # Malicious Debian package from deb.fdmpkg.org
  domain: freedownloadmanager.org # Official website that was compromised for redirection
  domain_type: project host
  artifact_type: binary archive # Malicious .deb installer
