- name: VSDC Video Editor
  title: VSDC download portal compromised
  synopsis: The official website of VSDC Video Editor was compromised multiple times. Attackers replaced legitimate download links with trojanized versions containing banking malware. Original source articles detailing the specifics are no longer accessible.
  start_date: 2018-11-01
  end_date: 2019-07-31
  attribution_type: Cybercriminal
  component_type: Application
  lang: C++
  cause: Website compromise
  motive: Financial gain
  transitive: false
  insertion_phase: distribution
  impact_type: Banking trojan
  impact_user_count: 565000
  historical_artifacts:
    - "Trojanized VSDC Video Editor installers downloaded from videosoftdev.com during 2018-2019."
  domain: videosoftdev.com
  domain_type: project download host
  artifact_type: binary archive
