- name: vestacp
  title: VestaCP build system compromise inserted remote backdoor
  synopsis: Attackers compromised infrastructure related to the Vesta Control Panel, allowing them to inject malicious code into update scripts or packages delivered to users. The malicious code executed commands, collected server passwords (including VestaCP admin and FTP passwords), and sent the stolen data to the attackers' server.
  start_date: 2018-06-01 # Approximate start of compromise
  end_date: 2018-06-12 # Date issue publicly acknowledged/addressed
  attribution_type: Cybercriminal gang
  component_type: Daemon # Hosting Control Panel
  lang: Shell # Malicious code in update scripts
  cause: Server compromise # Build/update infrastructure
  motive: Credential theft, Remote access
  insertion_phase: distribution # Compromise of update mechanism/packages
  impact_type: Credential theft, Remote execution, Backdoor
  domain: vestacp.com
  domain_type: project host
  artifact_type: Source archive
  references:
    - https://www.welivesecurity.com/2018/10/18/new-linux-chachaddos-malware-distributed-servers-vestacp-installed/
  versions:
    - All versions receiving updates during the compromise window
