- name: proftpd
  title: ProFTPD official site compromise distributes backdoored source
  repo: https://github.com/proftpd/proftpd
  synopsis: The main FTP server distributing the ProFTPD source code (`ftp.proftpd.org`) was compromised. Attackers replaced the legitimate source code tarball for ProFTPD version 1.3.3c with a modified version containing a backdoor. Compiling and running this version would allow attackers remote root access.
  start_date: 2010-11-28
  end_date: 2010-12-01 # Approximate discovery/replacement window
  attribution_type: Individual hacker
  component_type: Application # FTP Server
  lang: C # Backdoor inserted into C source
  cause: Server compromise # Official FTP distribution server hacked
  motive: Remote access # Root backdoor
  transitive: false
  insertion_phase: distribution # Official download source tarball replaced
  impact_type: Backdoor, Root compromise
  references:
    - https://www.theregister.com/2010/12/02/proftpd_backdoor/ # News report on the backdoor
    - https://lwn.net/Articles/418326/ # LWN coverage of the incident
    - https://www.linux-magazine.com/Online/News/ProFTPD-Backdoor-Discovered # Linux Magazine coverage
  versions:
    - 1.3.3c # Specific source tarball
  historical_artifacts:
    - ftp://ftp.proftpd.org/distrib/source/proftpd-1.3.3c.tar.gz # Original compromised download location
    - ftp://mirror.proftpd.org/proftpd-1.3.3c.tar.gz # Mirror potentially affected
  current_artifacts:
    - https://www.theregister.com/2010/12/02/proftpd_backdoor/ # Analysis with technical details
    - https://www.securityfocus.com/bid/45150 # SecurityFocus with backdoor details
  domain: ftp.proftpd.org
  domain_type: project host
  artifact_type: source archive
  hashes:
    - md5:565b57ceda4b00b80f896c5f44703291 # Backdoored proftpd-1.3.3c.tar.gz
  clean: true