- name: Kaseya VSA
  title: Kaseya VSA distributed REvil ransomware
  synopsis: Attackers exploited vulnerabilities in Kaseya VSA to distribute REvil ransomware through the software's auto-update functionality. The attack affected thousands of businesses worldwide.
  start_date: 2021-07-02
  end_date: 2021-07-05
  attribution_type: Cybercriminal gang
  component_type: Application
  lang: C#
  cause: Exploit
  motive: Financial gain
  transitive: false
  insertion_phase: CI/CD
  impact_type: Ransomware
  impact_user_count: 1500
  references:
    - https://www.cisa.gov/news-events/cybersecurity-advisories/aa21-201a
    - https://helpdesk.kaseya.com/hc/en-gb/articles/4403440684689-Kaseya-VSA-Security-Incident

  commits:
  historical_artifacts:
    - "https://update.kaseya.net/vsa/agent/hotfix"
    - "https://vsaupdate.kaseya.net/vsa/agent.crt"
    - "https://vsaupdate.kaseya.net/vsa/agent.exe"
  current_artifacts:
    - "https://community.sophos.com/sophos-labs/b/blog/posts/inside-a-revil-ransomware-attack"
    - "https://thehackernews.com/2021/07/how-kaseya-vsas-1-day-exploit-was.html"
    - "https://www.virustotal.com/gui/file/d55f983c994caa160ec63a59f6b4250fe67fb3e8c43a388aec60a4a6978e9f1e"
    - "https://github.com/curated-intel/Kaseya-Breach-Repository"
  hashes:
    - sha256:d55f983c994caa160ec63a59f6b4250fe67fb3e8c43a388aec60a4a6978e9f1e # Malicious agent.exe
    - sha256:8dd620d9aeb35960bb766458c8890ede987c33d239cf730f93fe49d90ae759dd # REvil ransomware dropper
    - sha256:0496ca57e387b10dbc85000f66a0bc8d47b710f9be26d11cd69051219fb4c070 # REvil ransomware payload
  domain: kaseya.com
  domain_type: project host
  artifact_type: binary archive
