- name: linux
  title: Linux kernel backdoor insertion attempt via CVS
  synopsis: An attacker attempted to insert a subtle backdoor into the Linux kernel source (kernel/exit.c) via the BitKeeper/CVS system. The change involved a two-line modification to the sys_wait4 function. If a call to wait4() was made with specific options (options == (__WCLONE|__WALL)), an additional check (`current->uid = 0`) would execute. This check, an assignment rather than a comparison, would set the calling process's UID to 0, granting root privileges. The attempt was detected and reverted before inclusion in any release.
  start_date: 2003-11-05
  end_date: 2003-11-05
  attribution_type: Nation-state # Speculated Nation-state or skilled hacker
  component_type: OS # Kernel
  lang: C
  cause: Compromised Infrastructure # Access to commit infrastructure (BitKeeper/CVS)
  motive: Espionage/Strategic Advantage # Hidden root access
  transitive: false
  insertion_phase: source # Attempted modification of authoritative source code
  impact_type: Benign/Proof of Concept # If it hadn't been caught
  references:
    - https://lwn.net/Articles/57237/
    - http://phrack.org/issues/62/4.html#article
  domain: bkbits.net
  domain_type: code host
  commits:
    - 1.121
    - 1.120
    - 1.119
    - 1.118
  historical_artifacts:
    - http://vger.kernel.org/bkmirror/linux-2.6/ # Archive of BitKeeper mirror
  current_artifacts:
    - https://lwn.net/Articles/57237/ # Discussion of the backdoor attempt and its code
  artifact_type: revision control system
