- name: openx
  title: OpenX ad server downloads compromised serving malware
  synopsis: The infrastructure serving downloads and updates for the OpenX Source ad server software was compromised. Attackers modified official software packages to include malicious code. This code redirected website visitors viewing ads served by compromised OpenX servers to the Styx exploit kit, infecting end-users.
  start_date: 2013-08-01 # Approximate start, active through Nov/Dec
  end_date: 2013-12-06 # Public disclosure and cleanup period
  attribution_type: Cybercriminal gang # Likely financially motivated group
  component_type: Application # Ad Server
  lang: PHP # Malicious code inserted into PHP application
  cause: Server compromise # Download/update infrastructure breached
  motive: Financial gain # Exploit kit distribution
  insertion_phase: distribution # Compromise of official download/update mechanism
  impact_type: Malware distribution, Remote execution # Via exploit kit
  references:
    - https://blog.sucuri.net/2013/12/openx-compromise-serving-malware.html
    - https://www.infosecurity-magazine.com/news/openx-ad-server-breach-serves-up-malware/
    - https://thehackernews.com/2013/12/openx-ad-serving-platform-hacked-to.html
  versions:
    - "OpenX Source 2.8.10" # At least this version confirmed affected
