- name: xzutils
  title: xz utils backdoor via social engineering, build modification
  synopsis: A sophisticated multi-year social engineering campaign resulted in an attacker gaining maintainership of xz utils. Malicious code was hidden in test files within the source repository and injected into the build process (configure script via m4 macro) only under specific conditions (x86-64 Linux, building .deb/.rpm with gcc/glibc). The backdoor targeted the OpenSSH server (sshd) linked against the compromised liblzma, enabling potential remote code execution by attackers possessing a specific private key.
  start_date: 2024-02-24 # Malicious code first included in release tarball (v5.6.0)
  end_date: 2024-03-29 # Backdoor discovered and publicly disclosed
  attribution_type: Nation-state # Suspected due to sophistication/patience
  component_type: Library # Compression utility/library
  lang: Shell # Build script modifications (m4/autoconf)
  cause: Sabotage # Maintainer access takeover
  motive: Espionage/Strategic Advantage # Remote access to sshd
  insertion_phase: build automation # Malicious code injected during configure/build stage
  impact_type: Backdoor/Remote Code Execution # Potential RCE via sshd compromise
  references:
    - https://nvd.nist.gov/vuln/detail/CVE-2024-3094
    - https://www.openwall.com/lists/oss-security/2024/03/29/4 # Initial disclosure by Andres Freund
    - https://research.swtch.com/xz-timeline # Detailed timeline by Russ Cox
    - https://web.archive.org/web/20240402162054/https://www.cisa.gov/news-events/alerts/2024/03/29/reported-supply-chain-compromise-affecting-xz-utils-data-compression-library # CISA Alert (Archived)
  versions:
    - 5.6.0
    - 5.6.1
  domain: github.com
  domain_type: code host
  artifact_type: source archive
  historical_artifacts:
    - https://github.com/tukaani-project/xz/releases/download/v5.6.0/xz-5.6.0.tar.gz
    - https://github.com/tukaani-project/xz/releases/download/v5.6.1/xz-5.6.1.tar.gz
  current_artifacts:
    - https://github.com/tukaani-project/xz/tree/release-5.6.1
    - https://research.swtch.com/xz-backdoor # Analysis with code samples
    - https://www.openwall.com/lists/oss-security/2024/03/29/4 # Initial disclosure with code analysis
  commits:
    - 9c45a8548eda244bd2127e2d2ae1a943c1affb12 # Initial malicious commit adding "cleanup" code
    - 61af4bc0f8cc25805e459cfa2ff011c80095daa6 # "xz: Fix assert which is often hit in fuzz testing" (concealing malicious code)
    - 70e9b1960fa77c5e45e9fb60db65a8ef8e0f438e # Malicious m4 macro for configure
  hashes:
    - sha256:64c34a523acb4925cf066c8e9ac66d53b0e7456e14364d12186616abc1e3c7ce # xz-5.6.1.tar.gz (contains malicious components)
    - sha256:ae2c4f079373aca8bcaf96225defedc0db2274686bcbec5f9e2d2ba344569345 # xz-5.6.0.tar.gz
