- name: eWON (HMS Networks)
  title: eWON VPN software installer distributed Havex.
  synopsis: Belgian ICS vendor eWON (later acquired by HMS Networks), which provides remote connectivity solutions like VPN software for industrial equipment, was targeted by the DragonFly campaign. Legitimate software installers for their products (e.g., eCatcher VPN client) available on their website were compromised to include the Havex RAT.
  start_date: 2013-01-01 # Approximate start of wider Havex campaign
  end_date: 2014-06-01 # Public disclosure and remediation period
  attribution_type: Nation-state # (DragonFly/Energetic Bear)
  component_type: Application # (VPN client/remote connectivity software)
  lang: C++ # (Havex RAT)
  cause: Website compromise # (Vendor website)
  motive: Espionage, Network reconnaissance
  transitive: false
  insertion_phase: distribution
  impact_type: Backdoor, Data theft, Remote access
  references:
    - https://threatpost.com/motives-behind-havex-ics-malware-campaign-remain-a-mystery/107046/ # Threatpost article
    - https://web.archive.org/web/20190717022917/https://www.symantec.com/content/en/us/enterprise/media/security_response/whitepapers/dragonfly-threat-against-energy-sector-systems.pdf # Symantec Dragonfly report (archived)
    - https://www.cisa.gov/news-events/ics-alerts/ics-alert-14-176-02a # CISA Alert on Havex/Dragonfly campaign
    - https://www.f-secure.com/documents/996508/1030745/Threat_Intelligence_Report_Havex_an_Energetic_Bear_Targets_ICS_SCADA.pdf # F-Secure Havex report
  versions:
    - Specific software installers for products like eCatcher during the compromise window.
  domain: ewon.biz # (Official vendor website at the time)
  domain_type: project download host
  artifact_type: binary archive
  historical_artifacts:
    - "Trojanized eWON eCatcher VPN client installer, downloaded from ewon.biz during 2013-2014."
    - "Compromised installer filename variations reported as: MBBActiveServ.exe, eCatcher_Setup.exe (specific names for eWON might vary, these are examples from the campaign)"
  current_artifacts:
    - "https://web.archive.org/web/20190717022917/https://www.symantec.com/content/en/us/enterprise/media/security_response/whitepapers/dragonfly-threat-against-energy-sector-systems.pdf" # Symantec Dragonfly report with IOCs
    - "https://www.f-secure.com/documents/996508/1030745/Threat_Intelligence_Report_Havex_an_Energetic_Bear_Targets_ICS_SCADA.pdf" # F-Secure Havex report with IOCs
    - "https://www.cisa.gov/news-events/ics-alerts/ics-alert-14-176-02a" # CISA Alert on Havex/Dragonfly campaign, lists compromised vendor software
    - "https://www.virustotal.com/gui/file/09a35ac2f7f9ca156c3a2ab2466c029976535390099101632e904a7ca3f6764d" # Example Havex RAT sample (SHA256)
  hashes:
    - sha256:09a35ac2f7f9ca156c3a2ab2466c029976535390099101632e904a7ca3f6764d # Havex RAT (Oldrea) payload
    - sha256:4a1a783a11c1a2a9d5915717b16ebb5012c685f4457a08246666d7d2f7dcb238 # Another common Havex RAT sample
    - md5:f691c8f16e290f829710ff0a18ff2532 # Havex component (client.dll)
