- name: node-ipc
  title: node-ipc NPM package maintainer adds protestware malware
  repo: https://github.com/RIAEvangelist/node-ipc
  synopsis: The maintainer added malicious code targeting users with Russian or Belarusian IP addresses. The code attempted to recursively overwrite files with a heart emoji character, causing data destruction. This 'protestware' was embedded within the popular `node-ipc` library.
  start_date: 2022-03-07 # Approximate date malicious code first introduced
  end_date: 2022-03-16 # Date widely reported and action taken
  attribution_type: Author
  component_type: Library
  lang: Javascript
  cause: Maintainer sabotage
  motive: Protest # Geopolitical protest
  transitive: false
  insertion_phase: source
  impact_type: Data destruction, Vandalism
  impact_user_count: 1000000 # Based on weekly downloads
  references:
    - https://snyk.io/blog/peacenotwar-protestware-node-ipc-package-vulnerability/
    - https://github.com/advisories/GHSA-97m3-w2cp-4xx6
    - https://arstechnica.com/information-technology/2022/03/sabotage-code-added-to-popular-npm-package-wiped-files-in-russia-and-belarus/
  versions:
    - 9.2.2
    - 10.1.1
    - 10.1.2
    - 11.0.0 # Specific versions containing the 'peacenotwar' module
  commits:
    - f3ff376905550597f05410771031cc67a446f662 # Example commit related to the module inclusion
  historical_artifacts:
    - https://registry.npmjs.org/node-ipc/-/node-ipc-9.2.2.tgz
    - https://registry.npmjs.org/node-ipc/-/node-ipc-10.1.1.tgz
    - https://registry.npmjs.org/node-ipc/-/node-ipc-10.1.2.tgz
    - https://registry.npmjs.org/node-ipc/-/node-ipc-11.0.0.tgz
  current_artifacts:
    - https://snyk.io/blog/peacenotwar-protestware-node-ipc-package-vulnerability/ # Analysis with code samples
    - https://github.com/RIAEvangelist/node-ipc/commit/f3ff376905550597f05410771031cc67a446f662 # Commit adding the malicious code
    - https://socket.dev/npm/package/node-ipc/versions # Historical version information
  domain: npmjs.org
  domain_type: package host
  artifact_type: source archive
  hashes:
    - sha256:f54bb89fe21762ce2ab5fe7581bf7f347f79ec30abe3ab1175da4edc26b5f91a # node-ipc-10.1.1.tgz
    - sha256:03190b659f9ad3c0e0bb337a958cbfa49c0bbfd8baff63d5a178c0eb6c8ea292 # node-ipc-10.1.2.tgz
