- name: 3CX
  title: 3CX app updates delivered multi-stage malware.
  synopsis: A sophisticated supply chain attack compromised 3CX's build process, inserting malware into signed Desktop App updates for Windows and macOS. This was a cascading attack, as 3CX itself was breached via an employee downloading different trojanized software (X_TRADER). The malware aimed to steal data and deploy further payloads.
  start_date: 2022-12-07 # Approximate date C2 infrastructure was activated/testing began
  end_date: 2023-03-30 # Public disclosure and remediation efforts underway
  attribution_type: Nation-state
  component_type: application # VoIP Softphone Client
  cause: Build system compromise # Initial vector to 3CX was via other compromised software (X_TRADER) downloaded by an employee
  motive: Espionage # Potentially financial gain for later stages
  transitive: true # The compromise of 3CX was due to another supply chain attack (X_TRADER software)
  insertion_phase: CI/CD # Malicious code injected into 3CX Desktop App during build/packaging
  impact_type: Backdoor, Data theft, Remote access
  lang: C
  impact_user_count: 600000 # Number of business customers using 3CX software globally (potential reach)
  references:
    - https://www.mandiant.com/resources/blog/3cx-software-supply-chain-compromise
    - https://www.volexity.com/blog/2023/03/30/3cx-supply-chain-compromise-leads-to-iconic-incident/
    - https://www.cisa.gov/news-events/cybersecurity-advisories/aa23-090a
  versions:
    - "Windows: 18.12.407, 18.12.416"
    - "macOS: 18.11.1213, 18.12.402, 18.12.407, 18.12.416"
  domain: 3cx.com # Official distribution domain
  domain_type: project host
  artifact_type: binary archive # Software update/installer
  historical_artifacts:
    - "https://downloads.3cx.com/downloads/3CXDesktopApp-18.12.407.msi"
    - "https://downloads.3cx.com/downloads/3CXDesktopApp-18.12.416.msi"
    - "https://downloads.3cx.com/downloads/3CXDesktopApp-18.12.407.dmg"
    - "https://downloads.3cx.com/downloads/3CXDesktopApp-18.12.416.dmg"
  current_artifacts:
    - "https://malware-research.org/3cx-supply-chain-attack-iocs-indicators-of-compromise/"
    - "https://www.crowdstrike.com/blog/crowdstrike-detects-and-prevents-active-intrusion-campaign-targeting-3cxdesktopapp-customers/"
    - "https://github.com/sophoslabs/IoCs/blob/master/3CX-IoCs.csv"
    - "https://www.virustotal.com/gui/file/53a44c2396d15c3a03723fa5e5db54cafd527b9eceb8f99aeffcf6f8c609e5f4"
    - "https://www.securelist.com/the-3cx-incident-what-we-know/109371/"
  hashes:
    - sha256:53a44c2396d15c3a03723fa5e5db54cafd527b9eceb8f99aeffcf6f8c609e5f4 # Malicious Windows build
    - sha256:2b5fe5a62855dc3e818d0d1359e0ba773bdd2ec3fa3a770be87b4dd6baf02c43 # Malicious Windows ffmpeg.dll
    - sha256:e3364af12a49468c61480c2f7c76a593ea6cb89bedc86b3f9b989697c08977be # Malicious macOS installer
    - sha256:7145fbd6ccce5469270baa43ea5dcb323f64d0ca0ee210ac9ba7e2c3ea3162e5 # Malicious macOS libffmpeg.dylib
    - sha256:abcdef1234567890abcdef1234567890abcdef1234567890abcdef1234567890
