- name: Volusion (via Google Cloud Storage script)
  title: Volusion e-commerce sites skimmed via script.
  synopsis: Over 29,500 e-commerce websites hosted on the Volusion platform were compromised when a malicious JavaScript file (volusion.js), hosted on a Google Cloud Storage bucket (storage.googleapis.com/volusionapi/resources/) used by Volusion, was modified. This script skimmed credit card information, exfiltrating it to gogogolo.com.
  start_date: 2019-10-07 # Approximate date of compromise
  end_date: 2019-10-09 # Approximate period of active skimming reported
  attribution_type: Cybercriminal gang # (Magecart)
  component_type: Script # (Platform-provided JavaScript)
  lang: JavaScript
  cause: Cloud storage compromise # (Compromised GCS bucket)
  motive: Financial gain
  transitive: true # Volusion customers affected due to compromise of Volusion's infrastructure
  insertion_phase: distribution # via Volusion's GCS-hosted script
  impact_type: Credential theft, Data theft
  impact_user_count: 29500 # Estimated number of Volusion stores potentially affected (TrendMicro reported at least 29,598)
  references:
    - https://blog.trendmicro.com/trendlabs-security-intelligence/volusion-platform-compromised-by-magecart-attackers-to-skim-credit-card-details/
  historical_artifacts:
    - //storage.googleapis.com/volusionapi/resources/volusion.js # Path to the compromised script
  current_artifacts:
    - https://blog.trendmicro.com/trendlabs-security-intelligence/volusion-platform-compromised-by-magecart-attackers-to-skim-credit-card-details/ # Contains deobfuscated skimmer code
    - "hxxps://www[.]gogogolo[.]com/pixel/pixel.js # Skimmer exfiltration domain"
  domain: storage.googleapis.com # (Infrastructure used by Volusion)
  domain_type: CDN host # (Effectively, for script delivery)
  artifact_type: source archive # (JavaScript file)
