- name: php
  title: PHP Git server compromise attempts source code backdoor
  repo: https://github.com/php/php-src
  synopsis: Attackers compromised the self-hosted `git.php.net` server. They pushed two malicious commits directly to the php-src repository ('main' branch). These commits attempted to insert a backdoor enabling remote code execution, disguised as typo fixes. The commits were detected quickly and did not impact any released version. PHP migrated to GitHub afterwards.
  start_date: 2021-03-28
  end_date: 2021-03-28
  attribution_type: Individual Hacker # Claimed to be Zerodium, but unconfirmed
  component_type: Library # Language runtime
  lang: C
  cause: Compromised Infrastructure # Git server credentials/access compromised
  motive: Espionage/Strategic Advantage # Remote code execution backdoor
  transitive: false
  insertion_phase: source # Direct commit to authoritative repository
  impact_type: Benign/Proof of Concept # If released
  references:
    - https://news-web.php.net/php.internals/113838 # Official announcement
    - https://www.bleepingcomputer.com/news/security/phps-git-server-hacked-to-add-backdoors-to-php-source-code/
    - https://github.com/php/php-src/issues/6900 # Discussion related to the incident
  commits:
    - c730aa26bd52829a49f2ad284b181b7e82a68d7d # First malicious commit (reverted)
    - 2b0f239b211c7544fcad542144ceca7d9b0ab58e # Second malicious commit (reverted)
  historical_artifacts:
    - https://git.php.net/?p=php-src.git;a=commit;h=c730aa26bd52829a49f2ad284b181b7e82a68d7d # Original malicious commit URL
    - https://git.php.net/?p=php-src.git;a=commit;h=2b0f239b211c7544fcad542144ceca7d9b0ab58e # Second malicious commit URL
  current_artifacts:
    - https://github.com/php/php-src/commit/c730aa26bd52829a49f2ad284b181b7e82a68d7d # Archive of first malicious commit
    - https://github.com/php/php-src/commit/2b0f239b211c7544fcad542144ceca7d9b0ab58e # Archive of second malicious commit
    - https://news-web.php.net/php.internals/113838 # Official announcement with technical details
  domain: git.php.net
  domain_type: code host
  artifact_type: revision control system
