- name: coa
  title: coa NPM package maintainer hijack distributes malware
  repo: https://github.com/veged/coa
  synopsis: Attacker compromised maintainer credentials for the 'coa' command-line argument parser library. Malicious versions were published containing password-stealing malware targeting Windows systems. This impacted downstream projects like 'rc'.
  start_date: 2021-11-04
  end_date: 2021-11-04
  attribution_type: Individual hacker
  component_type: Library
  lang: Javascript
  cause: Stolen credentials
  motive: Credential theft
  transitive: false
  historical_artifacts:
    - https://registry.npmjs.org/coa/-/coa-2.0.3.tgz
    - https://registry.npmjs.org/coa/-/coa-2.0.4.tgz
    - https://registry.npmjs.org/coa/-/coa-2.1.1.tgz
    - https://registry.npmjs.org/coa/-/coa-2.1.3.tgz
    - https://registry.npmjs.org/coa/-/coa-3.0.1.tgz
    - https://registry.npmjs.org/coa/-/coa-3.1.3.tgz
  current_artifacts:
    - https://socket.dev/npm/package/coa/versions # Shows version history including unpublished malicious ones
    - https://github.com/veged/coa/issues/99 # GitHub issue with community analysis and details of the malicious compile.js
  domain: npmjs.org
  domain_type: package host
  artifact_type: source archive
  insertion_phase: distribution
  impact_type: Credential theft
  references:
    - https://github.com/advisories/GHSA-73qr-pfmq-6rp8 # GitHub Advisory for coa
    - https://github.com/veged/coa/issues/99 # GitHub issue discussing the compromise
    - https://therecord.media/malware-found-in-coa-and-rc-two-npm-packages-with-23m-weekly-downloads/ # News report on coa and rc
  versions:
    - 2.0.3
    - 2.0.4
    - 2.1.1
    - 2.1.3
    - 3.0.1
    - 3.1.3
  hashes:
    - sha256:cd2adb9c16e3c5373f77c4288ab017be03c3a7f8320a2506e9129a402c0c69d6 # coa 2.0.4
    - sha256:dc7a59c2d600db8f748f0a722e363527e3332a0fd7ffd7d24342a7de6125e9e0 # coa 3.1.3
  clean: true
