- name: electron-native-notify
  title: electron-native-notify NPM package adds remote backdoor
  repo: https://github.com/calvinwyoung/electron-native-notify
  synopsis: The 'electron-native-notify' package was compromised to include malicious code. This code opened a reverse shell back to the attacker's server. It was used as a dependency in other applications, such as the Agama cryptocurrency wallet, leading to transitive compromises.
  start_date: 2018-08-01 # Approximate date malicious version appeared
  attribution_type: Unknown
  component_type: Library
  lang: Javascript
  cause: Unknown # Likely maintainer account compromise
  motive: Remote access # Potentially financial gain via crypto theft
  transitive: true # Impacted Agama wallet
  domain: npmjs.org
  domain_type: package host
  artifact_type: source archive
  insertion_phase: distribution
  impact_type: Backdoor, Remote access
  versions:
    - 1.1.6
