- name: electron-native-notify
  title: electron-native-notify NPM package adds remote backdoor
  repo: https://github.com/calvinwyoung/electron-native-notify
  synopsis: The 'electron-native-notify' package was compromised to include malicious code. This code opened a reverse shell back to the attacker's server. It was used as a dependency in other applications, such as the Agama cryptocurrency wallet, leading to transitive compromises.
  start_date: 2018-08-01 # Approximate date malicious version appeared
  attribution_type: Unknown
  component_type: Library
  lang: Javascript
  cause: Unknown # Likely maintainer account compromise
  motive: Remote access # Potentially financial gain via crypto theft
  transitive: true # Impacted Agama wallet
  domain: npmjs.org
  domain_type: package host
  artifact_type: source archive
  insertion_phase: distribution
  impact_type: Backdoor, Remote access
  references:
    - https://github.com/advisories/GHSA-j8qr-rvcv-crhv # GitHub Advisory
    - https://blog.npmjs.org/post/185397814280/plot-to-steal-cryptocurrency-foiled-by-the-npm # NPM Blog Post
    - https://www.npmjs.com/advisories/927 # NPM Advisory
    - https://github.com/eslint/eslint-scope/issues/39 # Initial GitHub issue reporting the compromised token
  versions:
    - 1.1.6
  historical_artifacts:
    - https://registry.npmjs.org/electron-native-notify/-/electron-native-notify-1.1.6.tgz
  current_artifacts:
    - https://blog.npmjs.org/post/185397814280/plot-to-steal-cryptocurrency-foiled-by-the-npm # NPM Blog Post with analysis
    - https://github.com/advisories/GHSA-j8qr-rvcv-crhv # GitHub Advisory with details
  hashes:
    - sha256:07f16d95f3c91dbd2ddf974d4b95d8dcec39b09b8906fa3b35e0a0da78fe8f76 # electron-native-notify 1.1.6
  clean: true
