- name: handbrake
  title: HandBrake Mac download mirror distributed Proton RAT
  synopsis: An official HandBrake download mirror server (download.handbrake.fr) hosting the macOS version was compromised. The HandBrake-1.0.7.dmg file was replaced with a malicious version containing the Proton Remote Access Trojan (RAT). Users downloading the Mac version from this mirror were infected.
  start_date: 2017-05-02 # Approximate start of compromise window
  end_date: 2017-05-06
  attribution_type: Individual hacker # Or group distributing Proton RAT
  component_type: Application
  lang: Binary # Malware was embedded in DMG
  cause: Server compromise # Mirror server hacked
  motive: Credential theft # Proton RAT capabilities
  insertion_phase: distribution # Compromise of official download mirror
  impact_type: Remote access, Credential theft
  references:
    - https://web.archive.org/web/20170507020635/https://forum.handbrake.fr/viewtopic.php?f=33&t=36361 (Original forum post, archived)
    - https://arstechnica.com/information-technology/2017/05/handbrake-download-server-hacked-to-distribute-mac-malware/
    - https://www.intego.com/mac-security-blog/handbrake-downloads-infected-with-new-proton-rat-variant/
  versions:
    - 1.0.7 # Specific Mac DMG file
  impacted_hashes:
    - 0935a43ca90c6c419a49e4f8f1d75e68cd70cb90b79306ce0cc7af2716aaa377 # SHA256 of the malicious HandBrake-1.0.7.dmg
