- name: vsftpd
  title: vsftpd official distribution site compromised distributing backdoor
  synopsis: The FTP server hosting the official vsftpd source code tarballs was compromised. For a brief period, the download for vsftpd version 2.3.4 was replaced with a version containing a backdoor. This backdoor opened a listening shell on TCP port 6200 when a username ending in ':)' was used to log in.
  start_date: 2011-07-03 # Approximate date/time of compromise
  end_date: 2011-07-03 # Discovered and removed very quickly
  attribution_type: Individual hacker
  component_type: Daemon # FTP Server
  lang: C # Backdoor code in C source
  cause: Server compromise # Master distribution site hacked
  motive: Remote access # Listening shell
  insertion_phase: distribution # Official download source tarball replaced
  impact_type: Backdoor, Remote execution
  references:
    - https://scarybeastsecurity.blogspot.com/2011/07/alert-vsftpd-download-backdoored.html # Author\'s blog post
    - https://www.rapid7.com/db/modules/exploit/unix/ftp/vsftpd_234_backdoor/ # Exploit module details
    - https://www.computerworld.com/article/2518230/vsftpd-developer-confirms-backdoor-in-version-2-3-4.html # News report
  domain: security.appspot.com
  domain_type: project host
  artifact_type: source archive
  versions:
    - 2.3.4 # Specific source tarball vsftpd-2.3.4.tar.gz
  historical_artifacts:
    - ftp://vsftpd.beasts.org/users/cevans/vsftpd-2.3.4.tar.gz # Original download location
    - http://security.appspot.com/downloads/vsftpd-2.3.4.tar.gz # Compromised mirror
  current_artifacts:
    - https://packetstormsecurity.com/files/154237/vsftpd-2.3.4-Backdoor.html # Analysis with sample code
    - https://github.com/kennetham/The_Practical_Guide_for_Information_System_Security/blob/master/backdoor_vsftpd_234.c # Sample of backdoor code
  hashes:
    - md5:a2bfd376c14ec3a83553c0c1aac0d1ff # Malicious vsftpd-2.3.4.tar.gz
    - sha1:26043b532863a0b354d0b7937ad7fed75c1b0a32 # Alternative hash of backdoored version
