- name: faker.js
  title: faker.js NPM package maintainer sabotage breaks apps
  repo: https://github.com/faker-js/faker
  synopsis: The maintainer of 'faker.js' intentionally sabotaged the library, similar to the 'colors.js' incident. As a protest, they force-pushed an 'endgame' commit that effectively emptied the project's code and published version 6.6.6 to NPM with a modified, non-functional state, disrupting dependent applications.
  start_date: 2022-01-04 # Approximate date of sabotage
  end_date: 2022-01-09 # When broader issue became known along with colors.js
  attribution_type: Author
  component_type: Library
  lang: Javascript
  cause: Maintainer sabotage
  motive: Protest
  transitive: false
  domain: npmjs.org
  domain_type: package host
  artifact_type: source archive
  insertion_phase: source
  impact_type: Vandalism, Data destruction # Deleted package content
  impact_user_count: 2800000 # Based on weekly downloads around the time
  references:
    - https://github.com/faker-js/faker/issues/1046
    - https://www.bleepingcomputer.com/news/security/dev-corrupts-npm-libs-colors-and-faker-breaking-thousands-of-apps/
  versions:
    - 6.6.6 # Specific version named in protest, though the main issue was repo deletion/corruption.
  commits:
    - c05c10e95447f11b0f5c98470eacd713e9a9e497 # Commit titled 'endgame'
  historical_artifacts:
    - https://registry.npmjs.org/faker/-/faker-6.6.6.tgz # Potential historical package URL
  current_artifacts:
    - https://github.com/faker-js/faker/commit/c05c10e95447f11b0f5c98470eacd713e9a9e497 # The "endgame" commit on GitHub
    - https://www.bleepingcomputer.com/news/security/dev-corrupts-npm-libs-colors-and-faker-breaking-thousands-of-apps/ # Article describing the event
    - https://snyk.io/blog/open-source-npm-packages-colors-faker-sabotaged/ # Snyk analysis with details
    - https://blog.sonatype.com/fakerjs-colorsjs-maintainer-intentionally-sabotages-popular-npm-libraries # Additional analysis
  hashes:
    - sha256:5234a5f7568a0d10977eeb898318c0f6567aeb1f2fa66939735e37a81f37bc39 # faker-6.6.6.tgz
    - sha1:c05c10e95447f11b0f5c98470eacd713e9a9e497 # The "endgame" commit hash
