- name: KSystem ERP
  title: KSystem ERP update program compromised.
  synopsis: Update program for KSystem ERP was compromised by the Andariel group. Malicious routines in `ClientUpdater.exe` deployed the Xctdoor backdoor, enabling data theft and remote control.
  start_date: 2024-03
  end_date: 2024-05
  attribution_type: Nation-state
  component_type: Application
  lang: C
  cause: Server compromise
  motive: Espionage, Data theft
  transitive: false
  insertion_phase: distribution
  impact_type: Data theft, Remote access, Backdoor
  references:
    - https://blog.ksystem.co.kr/%EB%B3%B4%EC%95%88%EC%B9%A8%ED%95%B4%EB%B0%A9%EC%A7%80%EB%A5%BC-%EC%9C%84%ED%95%9C-%EC%B7%A8%EC%95%BD%EC%84%B1-%EC%A0%90%EA%B2%80-%EC%A1%B0%EC%B9%98-%EC%95%88%EB%82%B4/?ckattempt=1
    - https://asec.ahnlab.com/en/74835/
  historical_artifacts:
    - devout.ksystem.co.kr
    - ClientUpdater.exe (via KSystem ERP update mechanism)
  current_artifacts:
    - https://www.virustotal.com/gui/file/ab8675b4943bc25a51da66565cfc8ac8
    - https://www.virustotal.com/gui/file/f24627f46ec64cae7a6fa9ee312c43d7
    - https://www.virustotal.com/gui/file/ad96a8f22faab8b9c361cfccc381cd28
    - https://www.virustotal.com/gui/file/9bbde4484821335d98b41b44f93276e8
  domain: ksystem.co.kr
  domain_type: project download host
  artifact_type: binary archive
  hashes:
    - md5:ab8675b4943bc25a51da66565cfc8ac8
    - md5:f24627f46ec64cae7a6fa9ee312c43d7
    - md5:ad96a8f22faab8b9c361cfccc381cd28
    - md5:9bbde4484821335d98b41b44f93276e8
    - md5:11465d02b0d7231730f3c4202b0400b8
    - md5:2e325935b2d1d0a82e63ff2876482956
