- name: agama
  title: Agama wallet compromised via malicious dependency backdoor
  repo: https://github.com/KomodoPlatform/Agama
  synopsis: The Agama cryptocurrency wallet application inadvertently included a compromised version of the `electron-native-notify` NPM package (v1.1.6) as a dependency in its builds. This resulted in official Agama wallet releases containing a backdoor (reverse shell) inherited from the dependency, potentially allowing attackers remote access and theft of wallet seeds or private keys.
  start_date: 2018-08-01 # Approximate date malicious dependency published/included in Agama builds
  end_date: 2018-08-13 # Date Komodo Platform issued warnings and advised updates
  attribution_type: Unknown # Same attribution as the electron-native-notify compromise
  component_type: Application # Cryptocurrency Wallet
  lang: Javascript # Wallet primarily JS/Electron; backdoor was JS
  cause: Dependency compromise # Malicious electron-native-notify included
  motive: Financial gain # Cryptocurrency theft
  transitive: true
  insertion_phase: dependency # Compromised dependency pulled during application build
  impact_type: Backdoor, Remote access, Credential theft # Wallet seeds/keys
  artifact_type: binary archive
  historical_artifacts:
    - pkg:github/KomodoPlatform/Agama@v0.3.3
    - pkg:github/KomodoPlatform/Agama@v0.3.4
  current_artifacts:
    - https://github.com/eslint/eslint-scope/issues/39 # Report on malicious electron-native-notify
    - https://github.com/eslint/eslint-scope/issues/39#issuecomment-404461211 # Malicious postinstall.js content from dependency (in comment)
    - https://blog.npmjs.org/post/185397814280/plot-to-steal-cryptocurrency-foiled-by-the-npm # NPM blog with analysis
  hashes:
    - sha256:07f16d95f3c91dbd2ddf974d4b95d8dcec39b09b8906fa3b35e0a0da78fe8f76 # electron-native-notify-1.1.6.tar.gz
  domain: github.com
  domain_type: code host
  references:
    - https://komodoplatform.com/vulnerability-discovered-in-komodos-agama-wallet-this-is-what-you-need-to-do/ # Official Komodo Platform warning
    - https://github.com/eslint/eslint-scope/issues/39 # Original report of the malicious electron-native-notify package
    - https://blog.npmjs.org/post/185397814280/plot-to-steal-cryptocurrency-foiled-by-the-npm # NPM blog with analysis of dependency
  versions:
    - 0.3.3 # Versions confirmed affected by Komodo advisory
    - 0.3.4 # Versions confirmed affected by Komodo advisory
    # Potentially other versions built using the compromised dependency during its availability
  clean: true
