- name: colors.js
  title: colors.js NPM package maintainer sabotage breaks apps
  repo: https://github.com/Marak/colors.js
  synopsis: The maintainer intentionally introduced an infinite loop and breaking changes into the popular 'colors.js' library. This act of sabotage disrupted applications depending on it, printing strange characters and causing denial of service. This was a protest act by the maintainer.
  start_date: 2022-01-07
  end_date: 2022-01-09
  attribution_type: Author
  component_type: Library
  lang: Javascript
  cause: Maintainer sabotage
  motive: Protest
  transitive: false
  domain: npmjs.org
  domain_type: package host
  artifact_type: source archive
  insertion_phase: source
  impact_type: Denial of service, Vandalism
  impact_user_count: 20000000 # Based on weekly downloads around the time
  references:
    - https://github.com/Marak/colors.js/issues/285
    - https://www.bleepingcomputer.com/news/security/dev-corrupts-npm-libs-colors-and-faker-breaking-thousands-of-apps/
  versions:
    - 1.4.1
    - 1.4.2
    - 1.4.44-liberty-2
  commits:
    - d11691a1a694899d8a543f027a368426350a2969
    - 6bc50e799061788799a73579c07683b499906d29
    - 8d817695d1e57a8011ba373d896985758850f03c
