- name: rc
  title: rc NPM package includes malicious coa dependency
  synopsis: The 'rc' configuration loader NPM package was compromised indirectly. Attackers gained control of the 'coa' package (a dependency) and published malicious versions. When 'rc' was updated to use these compromised 'coa' versions, 'rc' itself began distributing password-stealing malware transitively.
  start_date: 2021-11-04 # Date coa compromise impacted rc
  end_date: 2021-11-05 # Malicious versions removed
  attribution_type: Individual hacker # Same actor as coa compromise
  component_type: Library
  lang: Javascript
  cause: Dependency compromise # Malicious coa dependency added
  motive: Credential theft
  transitive: true
  insertion_phase: dependency # Malicious dependency specified
  impact_type: Credential theft
  impact_user_count: 10000000 # Based on weekly downloads of rc
  references:
    - https://github.com/advisories/GHSA-g2q5-5433-rhr4
    - https://nvd.nist.gov/vuln/detail/CVE-2021-43174
    - https://therecord.media/malware-found-in-npm-packages-coa-and-rc/
  versions:
    - 1.2.9
    - 1.3.9
    - 2.3.9
