- name: Microsoft Software Media
  title: Microsoft distribution media shipped with Form virus.
  synopsis: In 1995, Microsoft acknowledged accidentally distributing software installation floppy disks (reportedly including some for Windows 95 upgrades) infected with the common 'Form' boot sector virus. The infection likely occurred during mass disk duplication. While not destructive, the virus caused audible clicking sounds on infected PCs on the 18th of the month.
  start_date: 1995-01-01 # Approximate year of incident
  end_date: 1995-12-31 # Specific end date unclear, related to affected disk batches
  attribution_type: Accidental
  component_type: OS / Application # Specific product media not always confirmed
  cause: Manufacturing error # Contamination at disk duplication facility
  motive: Not applicable # Accidental
  transitive: false
  insertion_phase: distribution # Physical media duplication stage
  impact_type: Nuisance # Audible clicking sound payload
  references:
    - https://grahamcluley.com/ibm-shipping-malware-infected-usb-sticks/ # References the Microsoft/Form incident via comment/context
    - https://www.independent.co.uk/news/business/microsoft-ships-disks-infected-with-computer-virus-1575886.html # Contemporary news report (paywalled/snippet viewable)
    - https://arstechnica.com/information-technology/2010/08/the-viruses-microsoft-shipped/ # Discusses historical context
  versions:
    - "Specific batches of Microsoft software floppy disks circa 1995 (e.g., Windows 95 upgrade)"
  historical_artifacts:
    - "Infected Microsoft floppy disks"
  domain: microsoft.com
  domain_type: project download host
  artifact_type: floppy disk
