- name: "@solana/web3.js"
  title: "@solana/web3.js NPM package compromised stealing private keys"
  synopsis: Attackers compromised an NPM publish-access account, reportedly via spear-phishing a maintainer. They published malicious versions (1.95.6, 1.95.7) of the widely used `@solana/web3.js` package to NPM. The injected code captured private keys handled by dependent applications (especially bots or backend systems) and exfiltrated them to an attacker's server (`sol-rpc.xyz`), enabling cryptocurrency theft estimated around $160k USD.
  start_date: 2024-12-02 # Malicious versions published UTC
  end_date: 2024-12-03 # Malicious versions removed (~5 hour window)
  attribution_type: Individual hacker # Or group
  component_type: Library # Blockchain SDK
  lang: Javascript
  cause: Stolen credentials # Phishing attack
  motive: Financial gain # Cryptocurrency theft
  insertion_phase: distribution # Malicious versions published to NPM
  impact_type: Credential theft, Cryptocurrency theft
  impact_user_count: 400000 # Approximate weekly downloads; actual impacted count lower due to short window
  domain: npmjs.org
  domain_type: package host
  artifact_type: source archive
  historical_artifacts:
    - https://registry.npmjs.org/@solana/web3.js/-/web3.js-1.95.6.tgz
    - https://registry.npmjs.org/@solana/web3.js/-/web3.js-1.95.7.tgz
  current_artifacts:
    - https://www.cyfrin.io/blog/critical-security-alert-solana-web3-js-library-compromise # Analysis with code snippets
    - https://github.com/solana-labs/solana-web3.js/releases/tag/v1.95.8 # Release notes describing the compromise
  hashes:
    - sha256:cd9e0af30eee5b6935335e7969f9866d595b0c5301e15a2be54c9373f067f9d3 # web3.js-1.95.6.tgz
    - sha256:dc27c84a02208fb05e1a24a94eb4bed0108339e9ae31c6c9176a033ab4dcv55c # web3.js-1.95.7.tgz
  references:
    - https://nvd.nist.gov/vuln/detail/CVE-2024-54134 # Official CVE entry
    - https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2024-54134 # Mitre CVE entry
    - https://thehackernews.com/2024/12/researchers-uncover-backdoor-in-solanas.html # News report with details
    - https://www.cyfrin.io/blog/critical-security-alert-solana-web3-js-library-compromise # Security alert summary
    - https://github.com/solana-labs/solana-web3.js/releases/tag/v1.95.8 # Release notes mentioning the compromise
  versions:
    - 1.95.6
    - 1.95.7
