- name: transmission
  title: Transmission macOS installer distributed Keydnap backdoor
  repo: https://github.com/transmission/transmission
  synopsis: Months after the KeRanger incident, Transmission's website was compromised again. This time, the legitimate macOS installer for version 2.92 was replaced with a malicious version containing the OSX/Keydnap backdoor. Keydnap aimed to steal keychain credentials and establish persistent remote access.
  start_date: 2016-08-28 # Approximate date malicious file appeared
  end_date: 2016-08-30 # Approximate date discovered/removed
  attribution_type: Cybercriminal gang
  component_type: Application
  lang: Binary # Backdoor embedded in DMG
  cause: Server compromise # Website/download server hacked again
  motive: Credential theft, Remote access
  transitive: false
  insertion_phase: distribution # Official download file replaced
  impact_type: Credential theft, Backdoor, Remote access
  references:
    - https://objective-see.org/blog/blog_0x11.html # Patrick Wardle's analysis of Transmission 2.92 compromise with Keydnap
  versions:
    - 2.92 # Specific macOS DMG installer
  historical_artifacts:
    - https://download.transmissionbt.com/files/Transmission-2.92.dmg # Original compromised download location
    - https://updates.transmissionbt.com/Transmission-2.92.dmg # Alternate download path potentially affected
  current_artifacts:
    - https://objective-see.org/blog/blog_0x11.html # Analysis with technical details and screenshots
    - https://www.welivesecurity.com/2016/08/30/osxkeydnap-spreads-via-signed-transmission-application/ # Additional analysis with IOCs
  domain: transmissionbt.com 
  domain_type: project host
  artifact_type: binary archive
  hashes:
    - sha256:f06ac9609c3a8b00a7586840e990153460f8de9526e91a1a6ab733c850d5c83f # Malicious Transmission-2.92.dmg
    - sha256:c5e5ec89c5517b50d848b6a6d4f86ed74715a715a015c6d38d789addcffea6b3 # Keydnap malware component
