- name: Eltima Elmedia Player/Folx
  title: Eltima installers bundled Proton RAT.
  synopsis: Download servers for Eltima Software were compromised, leading to their Elmedia Player and Folx applications being bundled with the Proton Remote Access Trojan (RAT) for macOS.
  start_date: 2017-10-19 # Discovered, likely active before
  end_date: 2017-10-20 # Public notification
  attribution_type: Cybercriminal gang
  component_type: Application
  lang: Swift # Proton RAT
  cause: Server compromise
  motive: Financial gain, Data theft
  transitive: false
  insertion_phase: distribution
  impact_type: Backdoor, Remote access, Credential theft
  references:
    - https://www.bleepingcomputer.com/news/apple/eltima-website-hacked-to-spread-proton-rat-with-popular-video-player-app/
    - https://www.welivesecurity.com/2017/10/21/osxproton-supply-chain-attack-elmedia-player-folx/
    - https://web.archive.org/web/20171020215730/https://blog.eltima.com/security-breach-eltima-Oct-2017/ # Archived official Eltima blog post
  versions:
    - Elmedia Player (builds distributed on Oct 19th, 2017)
    - Folx (builds distributed on Oct 19th, 2017)
  domain: mac.eltima.com
  domain_type: project host
  artifact_type: binary archive
  historical_artifacts:
    - "https://mac.eltima.com/download/elmedia-player.dmg" # Compromised on Oct 19-20, 2017
    - "https://mac.eltima.com/download/folx.dmg" # Compromised on Oct 19-20, 2017
  current_artifacts:
    - "https://www.welivesecurity.com/2017/10/21/osxproton-supply-chain-attack-elmedia-player-folx/" # ESET analysis with IOCs
    - "https://www.virustotal.com/gui/file/e22f6a66442f8078a5da788998146208" # Malicious Elmedia Player DMG (MD5)
    - "https://www.virustotal.com/gui/file/1163587a698afe5d88a930c006f2e1e5" # Malicious Folx DMG (MD5)
    - "https://www.virustotal.com/gui/file/c59b518a610a000731504e0774e3051801972516" # Trojanized Eltima Player binary (SHA1)
    - "https://www.virustotal.com/gui/file/ce48791c014501d8811887f0404e1f0660769739" # Proton RAT sample (SHA1)
  hashes:
    - md5:e22f6a66442f8078a5da788998146208 # Malicious Elmedia Player DMG (OSX.Proton.A)
    - md5:1163587a698afe5d88a930c006f2e1e5 # Malicious Folx DMG (OSX.Proton.B)
    - sha1:c59b518a610a000731504e0774e3051801972516 # Trojanized Eltima Player.app binary
    - sha1:ce48791c014501d8811887f0404e1f0660769739 # Main Proton RAT sample (libcryptCHECK.dylib)
