- name: event-stream
  title: event-stream dependency steals Bitcoin wallets.
  repo: https://github.com/dominictarr/event-stream
  synopsis: The 'event-stream' npm package maintainership was transferred via social engineering to an attacker who then added 'flatmap-stream@0.1.1' as a dependency in 'event-stream@3.3.6'. This new dependency contained obfuscated, malicious code specifically designed to steal cryptocurrency (Bitcoin, Bitcoin Cash) from users of the Copay Dash wallet application by exfiltrating wallet data and private keys if balances exceeded certain thresholds.
  start_date: 2018-09-09
  end_date: 2018-11-26
  attribution_type: Individual hacker
  component_type: Library
  lang: javascript
  cause: Social engineering
  motive: Financial gain
  transitive: true
  insertion_phase: dependency
  impact_type: Cryptocurrency theft, Credential theft
  impact_user_count: 8000000
  references:
    - https://github.com/dominictarr/event-stream/issues/116 # Original GitHub issue reporting the exploit
    - https://blog.npmjs.org/post/180565383195/details-about-the-event-stream-incident # NPM Blog Post with details
    - https://www.npmjs.com/advisories/737 # NPM advisory for flatmap-stream (details malicious payload)
    - https://github.com/advisories/GHSA-9x64-5r7x-2q53 # GitHub advisory for flatmap-stream
  versions:
    - "3.3.6"
  historical_artifacts:
    - https://registry.npmjs.org/event-stream/-/event-stream-3.3.6.tgz
    - https://registry.npmjs.org/flatmap-stream/-/flatmap-stream-0.1.1.tgz
  current_artifacts:
    - https://www.npmjs.com/advisories/737 # NPM advisory for flatmap-stream (details malicious payload)
    - https://github.com/advisories/GHSA-9x64-5r7x-2q53 # GitHub advisory for flatmap-stream
    - https://github.com/dominictarr/event-stream/commit/e3163361fed01384c986b9b4c18feb1fc42b8285 # Commit adding flatmap-stream dependency
    - https://gist.github.com/ActualSize/ff5e2f52f9870d1158884129bb01084d # Gist with deobfuscated malicious flatmap-stream code
  domain: npmjs.org
  domain_type: package host
  artifact_type: source archive
  hashes:
    - sha1:10084752f5c006eb49b4abff6ff57d3a8abb5246 # event-stream 3.3.6
    - sha256:a9c97713c80d0ceb8f28038890af2a0d5f28a037726ed98e46cfa5e851ffec0d # flatmap-stream 0.1.1
  commits:
    - e3163361fed01384c986b9b4c18feb1fc42b8285 # Adding flatmap-stream dependency
