- name: Simply Houses
  title: Simply Houses mod compromised with Fracturiser malware
  synopsis: A developer account (`shyandlostboy81`) with publishing rights for the 'Simply Houses' Minecraft mod on CurseForge was compromised. Attackers uploaded a malicious JAR file disguised as a legitimate update. This file contained the 'Fracturiser' malware, designed to steal credentials (Discord, Microsoft, Minecraft) and spread to other JAR files on the user's system.
  start_date: 2023-05-01 # Approximate timeframe malicious files started appearing for various mods
  end_date: 2023-06-08 # Approximate date of widespread discovery and public warnings
  attribution_type: Unknown # Attacker(s) compromising accounts
  component_type: Game mod # Minecraft Java Edition Mod
  lang: Java
  cause: Stolen credentials # Compromised CurseForge/BukkitDev account
  motive: Credential theft, Malware propagation
  insertion_phase: distribution # Malicious JAR uploaded to official mod platform
  impact_type: Credential theft, Data theft, Malware infection
  domain: curseforge.com
  domain_type: package host
  artifact_type: binary archive
  historical_artifacts:
    - https://www.curseforge.com/minecraft/mc-mods/simply-houses # Original hosting location for the compromised mod
  current_artifacts:
    - https://github.com/fractureiser-investigation/fractureiser # GitHub repository with samples and analysis
    - https://github.com/fractureiser-investigation/fractureiser/blob/main/docs/stage1-analysis.md # Technical analysis
  hashes:
    - sha256:5584ac1f8b713d2f6310bd3cde425b775402fbc70e56e5e8d774bec15703ca79 # Malicious JAR hash
  references:
    - https://support.curseforge.com/en/support/solutions/articles/9000228509-june-2023-infected-mods-detection-tool-and-report # CurseForge Advisory listing affected projects
    - https://mineacademy.org/fractureiser-malware # Article listing affected mods
    - https://www.bitdefender.com/en-au/blog/labs/infected-minecraft-mods-lead-to-multi-stage-multi-platform-infostealer-malware # Technical analysis
  versions: # Specific versions varied, updates pushed around May/June 2023 were affected
