- name: event-stream
  title: event-stream NPM package maintainer change injects backdoor
  synopsis: A new maintainer was granted publishing rights to the popular 'event-stream' library. This maintainer added a malicious dependency ('flatmap-stream') containing obfuscated code. The code targeted developers using the Copay Bitcoin wallet application to steal cryptocurrency private keys.
  start_date: 2018-09-04 # Date flatmap-stream added
  end_date: 2018-11-26 # Date malicious package removed from NPM
  attribution_type: Individual hacker # Socially engineered maintainer access
  component_type: Library
  lang: Javascript
  cause: Social engineering # Maintainer handover
  motive: Financial gain # Cryptocurrency theft
  transitive: true # Added malicious dependency flatmap-stream
  insertion_phase: dependency
  impact_type: Credential theft, Cryptocurrency theft
  impact_user_count: 8000000 # Downloads of event-stream
  references:
    - https://github.com/dominictarr/event-stream/issues/116
    - https://medium.com/intrinsic/compromised-npm-package-event-stream-d47d08605502
    - https://blog.npmjs.org/post/180565383195/details-about-the-event-stream-incident
  versions:
    - ">=3.3.6" # Malicious code activated via flatmap-stream dependency
  artifacts:
    - url: https://github.com/dominictarr/event-stream/commit/5446870da3d748502593375652b41797a1457088 # Commit adding flatmap-stream
    - url: https://github.com/postmanlabs/postman-app-support/issues/5338 # Example of impacted downstream project
