- name: python (Official Docker Image)
  title: Python official Docker images include cryptominer malware
  repo: https://github.com/docker-library/python
  synopsis: Several official Python Docker image tags (including 3.9.7 and 3.10.0rc2 builds based on Debian Bullseye) hosted on Docker Hub were found to contain cryptomining malware (`libff.so`). The malicious code was unintentionally introduced into the images during the build/testing process on the build infrastructure, likely via a compromised third-party `.deb` package dependency. Affected images were quickly removed and replaced by the Docker security team and Python maintainers.
  start_date: 2021-09-21 # Approximate date affected images built/pushed
  end_date: 2021-10-01 # Approximate date issue discovered/images removed/advisory published
  attribution_type: Unknown # Actor who compromised the build dependency/environment
  component_type: Container Image # Official Docker Image
  lang: Binary # Cryptominer payload
  cause: Build environment compromise # Malicious dependency pulled during build/test
  motive: Financial gain # Cryptomining
  transitive: true
  insertion_phase: CI/CD # Compromised build environment/dependency injection during build
  impact_type: Resource hijacking, Cryptomining
  references:
    - https://www.docker.com/blog/docker-security-advisory-dsa-2021-001-potential-compromise-of-some-official-images/ # Docker security advisory
    - https://pythonspeed.com/articles/cryptominer-docker-image/ # Analysis of the incident
  versions: # Examples of affected tags built Sep 21-29, 2021
    - python:3.10.0rc2-bullseye
    - python:3.9.7-bullseye
    - python:3.10.0rc2-slim-bullseye
    - python:3.9.7-slim-bullseye
  historical_artifacts:
    - docker://python:3.10.0rc2-bullseye@sha256:fffeea4a2503e9f80f507898a448f3d760d7b78729a645151a656c3768799196
    - docker://python:3.9.7-bullseye@sha256:46911913680a4138f9479114a6349423302a7866b64073588f584a912b76a180
    - docker://python:3.10.0rc2-slim-bullseye@sha256:6509c01d354f517ee604a2d815df3c5813f991b490683290e997b9694656b6eb
    - docker://python:3.9.7-slim-bullseye@sha256:d132c510185b61177c2183564b0e835d630561bbf052c8eb42a6be9e97c6e1e7
  current_artifacts:
    - "https://web.archive.org/web/20211001195753/https://www.docker.com/blog/docker-security-advisory-dsa-2021-001-potential-compromise-of-some-official-images/" # Archived Docker security advisory
    - "https://pythonspeed.com/articles/cryptominer-docker-image/" # Analysis with technical details
  domain: hub.docker.com
  domain_type: container host
  artifact_type: OCI image
  hashes: # Examples of affected image digests from Docker advisory
    - sha256:fffeea4a2503e9f80f507898a448f3d760d7b78729a645151a656c3768799196 # python:3.10.0rc2-bullseye
    - sha256:46911913680a4138f9479114a6349423302a7866b64073588f584a912b76a180 # python:3.9.7-bullseye
    - sha256:6509c01d354f517ee604a2d815df3c5813f991b490683290e997b9694656b6eb # python:3.10.0rc2-slim-bullseye
    - sha256:d132c510185b61177c2183564b0e835d630561bbf052c8eb42a6be9e97c6e1e7 # python:3.9.7-slim-bullseye
    - sha256:c5623df482648cacece4f9652a0ae04b51e1cb0d4fc4eba3a312b75534cbb21a # Hash of the malicious libff.so file
