- name: faker.js
  title: faker.js NPM package maintainer sabotage breaks apps
  synopsis: Similar to 'colors.js', the maintainer intentionally corrupted the 'faker.js' library. This act of sabotage involved force-pushing breaking changes and effectively deleting the package content, causing disruption for dependent applications. This was also a protest act by the same maintainer.
  start_date: 2022-01-04 # Approximate date of sabotage
  end_date: 2022-01-09 # When broader issue became known along with colors.js
  attribution_type: Original maintainer
  component_type: Library
  lang: Javascript
  cause: Maintainer sabotage
  motive: Protest
  insertion_phase: source
  impact_type: Vandalism, Data destruction # Deleted package content
  impact_user_count: 2800000 # Based on weekly downloads around the time
  references:
    - https://github.com/faker-js/faker/issues/1046
    - https://www.bleepingcomputer.com/news/security/dev-corrupts-npm-libs-colors-and-faker-breaking-thousands-of-apps/
    - https://security.snyk.io/vuln/SNYK-JS-FAKER-2331906
  versions:
    - 6.6.6 # Specific version named in protest, though the main issue was repo deletion/corruption.
  commits:
    - c05c10e95447f11b0f5c98470eacd713e9a9e497 # Commit titled 'endgame'
