- name: Magento Extensions
  title: Magento extensions backdoored in coordinated supply chain attack.
  synopsis: Servers of multiple Magento extension vendors (including Tigren, Meetanshi, MGS) were compromised. Attackers injected PHP backdoors into at least 21 popular commercial extensions. The backdoors, some dormant for years but activated in 2025, allowed remote code execution on e-commerce stores using the compromised extensions.
  start_date: 2019-01-01 # Approximate earliest date backdoors were injected into some extensions
  end_date: 2025-04-20 # Approximate date attack/activation discovered (ongoing investigation likely)
  attribution_type: Unknown
  component_type: library # E-commerce platform extensions/modules
  cause: Vendor server compromise
  motive: Remote access # Likely for data theft (payment info, credentials) or further attacks
  transitive: false
  insertion_phase: distribution # Compromised vendor servers distributing infected code packages
  impact_type: Backdoor, Remote access, Data theft (potential)
  impact_user_count: 1000 # Estimated 500-1000 stores initially identified as affected
  references:
    - https://www.bleepingcomputer.com/news/security/magento-supply-chain-attack-compromises-hundreds-of-e-stores/
    - https://sansec.io/research/magento-supply-chain-attack-vendor-extensions # Sansec research details
    - https://gbhackers.com/hackers-exploit-21-apps-to-take-full-control/
  versions:
    - "Multiple versions of 21+ extensions from vendors Tigren, Meetanshi, MGS, potentially Weltpixel" # Specific list extensive, available in security reports
  historical_artifacts:
    - "https://tigren.com/m2/extensions/tigren-ajax-cart.zip"
    - "https://meetanshi.com/media/downloads/Meetanshi_SocialLogin-2.0.5.zip"
    - "https://magesolution.com/downloads/MGS_Fbuilder_v2.2.1.zip"
  current_artifacts:
    - "https://sansec.io/research/magento-supply-chain-attack-vendor-extensions"
    - "https://twitter.com/gwillem/status/1519986321786552321"
    - "https://github.com/gwillem/magento-malware-scanner/blob/master/rules/backend.txt"
  hashes:
    - sha256:e8edc2b931eb5b24a6fdc705add5685ab88e268d7c5179cb42c235a8192b10c1 # Backdoored License.php
    - md5:c8ed5ee17d5c95dbe8a9c3c73dc7043c # Backdoored MGS extension file
  domain: Multiple vendor websites # e.g., tigren.com, meetanshi.com, magesolution.com
  domain_type: project download host
  artifact_type: source archive # Extension code packages
