- name: rest-client
  title: rest-client Ruby gem compromised distributing backdoor malware
  synopsis: Maintainer accounts for the popular 'rest-client' Ruby gem were compromised multiple times. Attackers published malicious versions to RubyGems.org containing backdoors. These backdoors could steal credentials or execute arbitrary code on developer machines installing the gem.
  start_date: 2019-08-12 # Approximate date of first widely reported incident
  # end_date: # Multiple incidents occurred over time
  attribution_type: Individual hacker # Or group
  component_type: Library
  lang: Ruby
  cause: Stolen credentials # Maintainer account compromise
  motive: Credential theft, Remote execution
  insertion_phase: distribution # Malicious versions published to RubyGems.org
  impact_type: Credential theft, Backdoor, Remote execution
  references:
    - https://github.com/rest-client/rest-client/issues/713 # Discussion of 2019 incident
    - https://www.zdnet.com/article/two-ruby-libraries-downloaded-1500-times-contain-backdoor-code/ # Covers rest-client & strong_password
    - https://securityboulevard.com/2019/08/rubygems-compromised-malware-found-in-rest-client-package/
  versions:
    - 1.6.13 # Example compromised version from 2019 incident
    # Other versions were also compromised in subsequent incidents
