- name: openssh
  title: OpenSSH CVS source code backdoor attempt discovered
  synopsis: Malicious code attempting to create a backdoor was discovered in the OpenBSD CVS repository, affecting OpenSSH code. The backdoor would trigger during challenge-response authentication, potentially allowing remote access. It was inserted by a core developer, allegedly under duress (FBI coercion claim, later doubted). The code was found and removed before any vulnerable release.
  start_date: 2002-08-31 # Approximate date of insertion
  end_date: 2002-09-01 # Date of discovery/revert
  attribution_type: Unknown # Potentially coerced
  component_type: Application # Foundational security tool
  lang: C
  cause: Developer insertion # Motivation disputed (coercion vs internal)
  motive: Espionage # Remote access
  transitive: false
  insertion_phase: source # Direct commit to CVS repository
  impact_type: Potential remote access # If released
  references:
    - https://marc.info/?l=openbsd-security-announce&m=103302809430059&w=2 # Original OpenBSD announcement
    - https://www.theregister.com/2002/09/03/trojan_horse_discovered_in_openssh/ # News report of the incident
    - https://lwn.net/Articles/9571/ # LWN coverage of the incident
  historical_artifacts:
    - cvs://anoncvs.openbsd.org/src/usr.bin/ssh/auth2-chall.c#revision=1.100 # CVS revision with backdoor
    - ftp://ftp.openbsd.org/pub/OpenBSD/OpenSSH/openssh-3.4p1.tar.gz # Source distribution that could have included the backdoor
  current_artifacts:
    - https://marc.info/?l=openbsd-security-announce&m=103302809430059&w=2 # Analysis with code excerpt
    - https://www.securityfocus.com/news/625 # Security Focus article with technical details
  commits:
    - "Revision 1.100 of ssh/auth2-chall.c" # Location of the backdoored code
  domain: openbsd.org
  domain_type: code host
  artifact_type: revision control system
  hashes:
    - sha1:a49a3636610c5f10c27f5c71072ce4cff5baffc3 # Backdoored auth2-chall.c file
