- name: openssh
  title: Trojan Horse in OpenSSH Distribution Files
  synopsis: Malicious code was discovered in OpenSSH distribution files on the official OpenBSD FTP server. The trojan was inserted into the source code archives and would activate during compilation, connecting to a remote server on IRC port 6667 and allowing arbitrary command execution. The backdoor was discovered quickly and the compromised files were replaced with clean versions before widespread damage could occur.
  start_date: 2002-07-30 # Approximate date of insertion
  end_date: 2002-08-01 # Date of discovery/removal
  attribution_type: Unknown # No public attribution
  component_type: Application # Security/cryptography software
  lang: C
  cause: Sabotage # Intentional insertion of malicious code
  motive: Unauthorized Access/Control # Command execution backdoor
  transitive: false
  insertion_phase: distribution # Inserted into distribution files
  impact_type: Limited # Quick detection limited impact
  references:
    - https://www.openssh.com/txt/trojan.adv
    - https://undeadly.org/cgi?action=article&sid=20020801122759
    - https://www.itworldcanada.com/article/trojan-horse-found-in-openssh/25256
    - https://www.cert.org/advisories/CA-2002-24.html
    - https://www.mavetju.org/unix/openssh-trojan.php
    - https://slashdot.org/comments.pl?sid=37188&cid=3991288
  historical_artifacts:
    - ftp://ftp.openbsd.org/pub/OpenBSD/OpenSSH/openssh-3.4p1.tar.gz # Trojaned distribution file
    - ftp://ftp.openbsd.org/pub/OpenBSD/OpenSSH/openssh-3.4.tgz # Trojaned distribution file
    - ftp://ftp.openbsd.org/pub/OpenBSD/OpenSSH/openssh-3.2.2p1.tar.gz # Trojaned distribution file
  current_artifacts:
    - http://www.mavetju.org/~edwin/bf-test.c # Preserved copy of the malicious file
    - http://www.mavetju.org/~edwin/bf-output.sh # Generated shell script
  commits:
    - None # The attack was on distribution files, not repository commits
  domain: openssh.com
  domain_type: code distribution
  artifact_type: tar archive
  versions:
    - 3.2.2p1
    - 3.4p1
    - 3.4
  hashes:
    - 3ac9bc346d736b4a51d676faa2a08a57 # MD5 of trojaned openssh-3.4p1.tar.gz
