- name: "WinSCP"
  title: "WinSCP installer compromised by hackers"
  start_date: "2024-03-07"
  end_date: "2024-03-08"
  license: "GPL-3.0"
  website: "https://winscp.net/"
  repo: "https://github.com/winscp/winscp"
  attribution_type: "unknown"
  component_type: "Application"
  lang: "C++"
  cause: "compromise"
  motive: "malware distribution"
  attack_vector: "website compromise"
  insertion_phase: "distribution"
  impact_type: "malware dropper"
  references:
    - "https://winscp.net/eng/docs/security_20240308"
    - "https://www.bleepingcomputer.com/news/security/winscp-says-site-was-hacked-to-distribute-trojanized-installers/"
  versions:
    - "6.3.2"
  synopsis: "Attackers compromised the WinSCP website and replaced the official installer with a trojanized version. The malicious installer contained a dropper that would install the legitimate WinSCP application while secretly deploying additional malware."
  compromise_desc: "Unknown attackers breached the WinSCP website and replaced the official WinSCP installer with a malicious variant. The attack lasted for approximately 14 hours between March 7-8, 2024. The attackers modified download links for the official installer to point to their compromised version."
  impact_desc: "The malicious installer functioned as a dropper that would install the legitimate WinSCP application while simultaneously deploying additional malware. The full scope of the additional malware's capabilities wasn't disclosed, but users who downloaded WinSCP during the attack window were advised to scan their systems and reinstall the application from a clean source."
