- name: linux_mint
  title: Linux Mint website hack redirects ISO downloads
  synopsis: The Linux Mint website, specifically its WordPress installation, was compromised. Attackers modified download links on the site for the Linux Mint 17.3 Cinnamon edition ISO. These links redirected users to a server hosting a modified ISO containing the Tsunami backdoor, giving attackers remote control over infected machines.
  start_date: 2016-02-20
  end_date: 2016-02-21
  attribution_type: Individual hacker # Group ('peace') claimed responsibility later for forum db leak, maybe related?
  component_type: Distribution # Linux Distribution website/ISO
  lang: Binary # Backdoor in ISO image, likely C/Shell based
  cause: Exploit # WordPress vulnerability exploited
  motive: Remote access # Botnet creation or espionage
  insertion_phase: distribution # Compromise of official download website links
  impact_type: Backdoor, Remote access
  references:
    - https://blog.linuxmint.com/?p=2994 # Original announcement
    - https://www.zdnet.com/article/linux-mint-hacked-iso-downloads-replaced-with-backdoored-ones/
    - https://www.wordfence.com/blog/2016/02/linux-mint-website-hack-leads-malware-infected-isos/
  versions:
    - "17.3 Cinnamon Edition" # Specific ISO targeted
