- name: Unix C Compiler (Bell Labs Experiment)
  title: Ken Thompson implements compiler backdoor demo
  synopsis: In his 1983 Turing Award lecture (published 1984), Ken Thompson described an experiment he likely implemented years earlier at Bell Labs. He modified the Unix C compiler (`cc`) binary to insert a backdoor into the `login` program during compilation. The compiler was also modified to recognize its own source code and inject both the `login` backdoor logic and the self-replicating compiler modification into any newly compiled compiler binary, even from clean source. This practical demonstration highlighted the fundamental vulnerability of trusting software built with potentially compromised toolchains.
  start_date: 1983-07-01
  end_date: 1983-08-01
  attribution_type: Author
  component_type: Compiler
  lang: C / Assembly # Language of Unix tools
  cause: Sabotage # As a proof of concept/experiment
  motive: Experimentation/Notoriety # Demonstrating trust vulnerability
  transitive: true
  historical_artifacts:
    - unix:/usr/bin/cc # Original Bell Labs Unix compiler
    - unix:/bin/login # The login program that was backdoored
  current_artifacts:
    - https://www.cs.cmu.edu/~rdriley/487/papers/Thompson_1984_ReflectionsonTrustingTrust.pdf # Paper containing technical details
    - https://wiki.c2.com/?TheKenThompsonHack # Documentation of the backdoor technique
  insertion_phase: source
  impact_type: Benign/Proof of Concept # Implemented within Bell Labs, not maliciously distributed
  artifact_type: binary archive
  references:
    - https://www.cs.cmu.edu/~rdriley/487/papers/Thompson_1984_ReflectionsonTrustingTrust.pdf # Widely available PDF copy
    - https://niconiconi.neocities.org/posts/ken-thompson-really-did-launch-his-trusting-trust-trojan-attack-in-real-life/ # Blog post discussing evidence of actual implementation
    - https://dl.acm.org/doi/10.1145/358198.358210 # Original ACM publication
  versions: # Experiment within Bell Labs, not tied to specific public distribution versions
    - Early Unix versions (Bell Labs internal)
