- name: node-ipc
  title: node-ipc NPM package maintainer adds protestware malware
  synopsis: The maintainer added malicious code targeting users with Russian or Belarusian IP addresses. The code attempted to recursively overwrite files with a heart emoji character, causing data destruction. This 'protestware' was embedded within the popular `node-ipc` library.
  start_date: 2022-03-07 # Approximate date malicious code first introduced
  end_date: 2022-03-16 # Date widely reported and action taken
  attribution_type: Original maintainer
  component_type: Library
  lang: Javascript
  cause: Maintainer sabotage
  motive: Protest # Geopolitical protest
  insertion_phase: source
  impact_type: Data destruction, Vandalism
  impact_user_count: 1000000 # Based on weekly downloads
  references:
    - https://github.com/RIAEvangelist/node-ipc/issues/233
    - https://snyk.io/blog/peacenotwar-protestware-node-ipc-package-vulnerability/
    - https://www.bleepingcomputer.com/news/security/big-sabotage-nodejs-package-wipes-files-to-protest-ukraine-war/
  versions:
    - 9.2.2
    - 10.1.1
    - 10.1.2
    - 11.0.0 # Specific versions containing the 'peacenotwar' module
  commits:
    - f3ff376905550597f05410771031cc67a446f662 # Example commit related to the module inclusion
