- name: strong_password
  title: strong_password Ruby gem compromised with backdoor code
  synopsis: Similar to the 'rest-client' incident around the same time, the 'strong_password' Ruby gem had a malicious version published. This compromised version contained a backdoor designed to steal environment variables and potentially execute code. It's suspected the same actor compromised both gems.
  start_date: 2019-08-16 # Approximate date malicious version published
  end_date: 2019-08-21 # Date malicious version discovered/removed
  attribution_type: Individual hacker # Or group (linked to rest-client)
  component_type: Library
  lang: Ruby
  cause: Stolen credentials # Maintainer account compromise
  motive: Credential theft, Remote execution
  insertion_phase: distribution # Malicious version published to RubyGems.org
  impact_type: Credential theft, Backdoor
  domain: rubygems.org
  domain_type: package host
  artifact_type: source archive
  references:
    - https://github.com/rest-client/rest-client/issues/713 # Covers both rest-client and strong_password
    - https://snyk.io/blog/code-execution-back-door-found-in-rubys-rest-client-library/ # Mentions strong_password
    - https://www.helpnetsecurity.com/2019/08/21/backdoored-ruby-gems/ # Discusses both gems
  versions:
    - 0.0.7
  historical_artifacts:
    - https://rubygems.org/gems/strong_password/versions/0.0.7 # Original compromised version
    - https://rubygems.org/downloads/strong_password-0.0.7.gem # Direct download link
  current_artifacts:
    - https://snyk.io/blog/code-execution-back-door-found-in-rubys-rest-client-library/ # Analysis mentioning the backdoor
    - https://www.helpnetsecurity.com/2019/08/21/backdoored-ruby-gems/ # Technical analysis with details
  hashes:
    - sha256:c3a46b979b941ecc456639033754f3bad3f5d379df064d4ccd0b54d0fb8e46ea # strong_password-0.0.7.gem