- name: Picreel (via pop-up script)
  title: Picreel pop-up script delivered skimmer.
  synopsis: Picreel, a service providing conversion rate optimization tools like exit pop-ups, had its JavaScript code compromised. Attackers modified the script served to Picreel's clients, injecting a credit card skimmer that affected the websites of businesses using Picreel's services.
  start_date: 2019-01-01 # Approximate, part of broader Magecart campaigns in 2019
  end_date: 2019-05-01 # Approximate discovery and reporting period
  attribution_type: Cybercriminal gang # (Magecart)
  component_type: Script # (Marketing/Analytics script)
  lang: JavaScript
  cause: Compromised third-party script # (Picreel's script)
  motive: Financial gain
  transitive: true # Picreel's customers affected
  insertion_phase: dependency # From the perspective of websites using Picreel
  impact_type: Credential theft, Data theft
  references:
    - "https://medium.com/sanguine-security-labs/popular-analytics-service-picreel-hacked-to-skim-credit-cards-f88b39905502 # Original Sanguine Labs (Sansec) analysis (Link confirmed dead, needs alternative)"
    - "https://www.bleepingcomputer.com/news/security/picreel-conversion-platform-hacked-to-steal-credit-cards/ # BleepingComputer report (Link confirmed dead, needs alternative)"
  domain: picreel.com # (Service provider's domain)
  domain_type: project host
  artifact_type: source archive # (JavaScript file)
  historical_artifacts:
    - "Compromised JavaScript files served by Picreel to its clients via picreel.com, active around early 2019."
  current_artifacts:
    - "https://medium.com/sanguine-security-labs/popular-analytics-service-picreel-hacked-to-skim-credit-cards-f88b39905502 # Original Sanguine Labs (Sansec) analysis (Link confirmed dead, needs alternative or removal)"
    - "https://www.bleepingcomputer.com/news/security/picreel-conversion-platform-hacked-to-steal-credit-cards/ # BleepingComputer report (Link confirmed dead, needs alternative or removal)"
