- name: Passwordstate
  title: Passwordstate update pushed Moserpass credential stealer.
  synopsis: The update mechanism for the Passwordstate enterprise password manager was compromised by an unknown actor. For approximately 28 hours, the system distributed a malicious update containing the 'Moserpass' malware, designed to exfiltrate system information and stored Passwordstate credential data.
  start_date: 2021-04-20T20:33:00Z # UTC time malicious update became available
  end_date: 2021-04-22T00:30:00Z # UTC time malicious update was removed
  attribution_type: Unknown attacker
  component_type: application # Enterprise password manager
  cause: Update mechanism compromise # Vendor's update process/server breached
  motive: Credential theft, Data theft
  transitive: false
  insertion_phase: distribution # Compromised update delivered via official channel
  impact_type: Credential theft, Data exfiltration
  impact_user_count: 1000 # Estimate; affected subset of 29k customer organizations who updated during the window
  references:
    - "https://www.csis.dk/newsroom-blog-overview/2021/moserpass/ # CSIS Group analysis (Link confirmed dead, needs alternative)"
    - "https://www.bleepingcomputer.com/news/security/passwordstate-password-manager-breached-via-supply-chain-attack/ # (Link confirmed dead, needs alternative)"
    - "https://socprime.com/blog/passwordstate-supply-chain-attack-exposes-29k-companies-to-the-risk-of-compromise/ # (Link confirmed dead, needs alternative)"
    - "https://www.clickstudios.com.au/passwordstate-supply-chain-attack-information.html # Original vendor advisory page (Link confirmed dead/server error, needs alternative)"
  versions:
    - "Passwordstate In-Place Upgrades performed between Apr 20 20:33 UTC and Apr 22 00:30 UTC, 2021"
  historical_artifacts:
    - "https://passwordstate-18667.kxcdn.com/passwordstate/upgrades/Passwordstate_upgrade.zip"
    - "https://updates.clickstudios.com.au/passwordstate/upgrades/Passwordstate_upgrade.zip"
  current_artifacts:
    - "https://www.virustotal.com/gui/file/502bf5e87e1809e6b2317888fab546aa1d22389922d83bb81a35b602ed12c23e" # Malicious Passwordstate_upgrade.zip
    - "Original CSIS Group analysis (link dead): https://www.csis.dk/newsroom-blog-overview/2021/moserpass/"
    - "Original ESET IoC link (link dead): https://github.com/eset/malware-ioc/tree/master/moserpass"
  domain: clickstudios.com.au # Vendor domain associated with updates
  domain_type: project host
  artifact_type: binary archive # Software update package
  hashes:
    - sha256:502bf5e87e1809e6b2317888fab546aa1d22389922d83bb81a35b602ed12c23e # Malicious Passwordstate_upgrade.zip
    - sha256:e5ca693512ae940f1058ef2ffb6a3cb560661a9e5b78e9fea7a25dee4c7f65a9 # moserware.secretsplitter.dll
    - sha256:3559ef72396bc0bf5e8874cf5710a5aa0eef72c4b27af32e1f72ed5bacf9a271 # Second-stage DLL
  commits:
