- name: Passwordstate
  title: Passwordstate update pushed Moserpass credential stealer.
  synopsis: The update mechanism for the Passwordstate enterprise password manager was compromised by an unknown actor. For approximately 28 hours, the system distributed a malicious update containing the 'Moserpass' malware, designed to exfiltrate system information and stored Passwordstate credential data.
  start_date: 2021-04-20T20:33:00Z # UTC time malicious update became available
  end_date: 2021-04-22T00:30:00Z # UTC time malicious update was removed
  attribution_type: Unknown attacker
  component_type: application # Enterprise password manager
  cause: Update mechanism compromise # Vendor's update process/server breached
  motive: Credential theft, Data theft
  transitive: false
  insertion_phase: distribution # Compromised update delivered via official channel
  impact_type: Credential theft, Data exfiltration
  impact_user_count: 1000 # Estimate; affected subset of 29k customer organizations who updated during the window
  references:
    - https://www.csis.dk/newsroom-blog-overview/2021/moserpass/ # CSIS Group analysis
    - https://www.bleepingcomputer.com/news/security/passwordstate-password-manager-breached-via-supply-chain-attack/
    - https://socprime.com/blog/passwordstate-supply-chain-attack-exposes-29k-companies-to-the-risk-of-compromise/
    - https://www.clickstudios.com.au/passwordstate-supply-chain-attack-information.html # Original vendor advisory page (may change)
  versions:
    - "Passwordstate In-Place Upgrades performed between Apr 20 20:33 UTC and Apr 22 00:30 UTC, 2021"
  artifacts:
    - "Passwordstate_upgrade.zip" # Malicious update archive name
    - "moserware.secretsplitter.dll" # Malicious DLL within the update
    - "Moserpass" # Name given to the malware
  domain: clickstudios.com.au # Vendor domain associated with updates
  domain_type: project host
  artifact_type: binary archive # Software update package
