- name: pear
  title: PEAR PHP installer go-pear.phar compromised on server
  synopsis: The official `go-pear.phar` installer file hosted on the `pear.php.net` server was compromised and replaced with a malicious version. Users downloading and executing this compromised installer could have had their systems backdoored. The compromise lasted approximately six months before discovery.
  start_date: 2018-06-20 # Estimated start based on file timestamp (may vary)
  end_date: 2019-01-19
  attribution_type: Unknown
  component_type: Library # Package manager/installer
  lang: PHP
  cause: Server compromise # pear.php.net server hacked
  motive: Unknown # Potential backdoor/further access
  transitive: false
  insertion_phase: distribution # Official download file replaced
  impact_type: Potential backdoor, Remote execution
  references:
    - https://thehackernews.com/2019/01/php-pear-hacked.html # News coverage
    - https://blog.paranoidpenguin.net/2019/01/pear-php-net-probably-compromised/ # Early analysis
    - https://twitter.com/pear/status/1086934578562560001 # Original announcement
  historical_artifacts:
    - http://pear.php.net/go-pear.phar # Original URL of the compromised file (now serves clean version)
    - http://web.archive.org/web/20190119035624/http://pear.php.net/go-pear.phar # Archive snapshot during compromise period
  current_artifacts:
    - https://www.bleepingcomputer.com/news/security/official-php-pear-website-suffers-supply-chain-attack/ # Analysis with technical details
    - https://blog.paranoidpenguin.net/2019/01/pear-php-net-probably-compromised/ # Analysis with details on malicious code
  domain: pear.php.net
  domain_type: project download host
  artifact_type: binary archive
  hashes:
    - sha1:1e623a48b8991980e93896153651135ab7ab82a0 # Compromised go-pear.phar file
