- name: gentoo
  title: Gentoo GitHub hack modified ebuilds
  repo: https://github.com/gentoo
  synopsis: An attacker gained control of Gentoo's GitHub organization administrator account (reportedly 'risacher' via password guessing). The attacker modified content, including ebuilds for 'portage' and 'musl-dev' in the main Gentoo ebuild repository, replacing them with malicious versions designed to execute 'rm -rf /' which would attempt to remove all files from users' systems. Access was quickly regained and changes reverted.
  start_date: 2018-06-28
  end_date: 2018-06-28
  attribution_type: Individual hacker
  component_type: Distribution # Linux Distribution infrastructure/packages
  lang: Shell # Ebuilds are shell scripts
  cause: Stolen credentials # Password guessed via insecure practices
  motive: Unknown # Vandalism or attempted deeper compromise
  transitive: false
  insertion_phase: source # Modification of source code/package definitions on GitHub
  impact_type: Data destruction, Potential remote execution # Malicious ebuilds attempted 'rm -rf /'
  references:
    - https://arstechnica.com/information-technology/2018/06/gentoo-linux-github-organization-hacked-and-defaced/ # Ars Technica article
  versions:
    - Various ebuilds and scripts hosted on GitHub at the time of compromise
  commits:
    - b8ed5a815dfb8c077a92e6a3a90c1ae6a88d284d # Example of compromised commit through 'risacher' account
    - 2bd555a1138cb197271e8ddeec38bf4c7ae71844 # Another potentially malicious commit that was reverted
  historical_artifacts:
    - https://github.com/gentoo/gentoo/commit/b8ed5a815dfb8c077a92e6a3a90c1ae6a88d284d # Repository during compromise
    - https://github.com/gentoo-mirror/gentoo/archive/refs/heads/master.zip # Snapshot of repo during compromise
  current_artifacts:
    - https://wiki.gentoo.org/wiki/Github/2018-06-28_incident # Official Gentoo wiki page documenting the incident
    - https://security.gentoo.org/glsa/201807-01 # Gentoo Security Advisory
  domain: github.com
  domain_type: code host
  artifact_type: revision control system
  hashes:
    - sha1:b8ed5a815dfb8c077a92e6a3a90c1ae6a88d284d # Malicious commit hash
    - sha1:2bd555a1138cb197271e8ddeec38bf4c7ae71844 # Another malicious commit hash
  clean: true
