- name: gentoo
  title: Gentoo GitHub organization compromise modified ebuilds
  synopsis: An attacker gained control of Gentoo's GitHub organization administrator account. The attacker modified content, including ebuild package scripts, potentially inserting malicious code. Access was quickly regained and changes reverted.
  start_date: 2018-06-28
  end_date: 2018-06-28
  attribution_type: Individual hacker
  component_type: Distribution # Linux Distribution infrastructure/packages
  lang: Shell # Ebuilds are shell scripts
  cause: Stolen credentials # Password guessed via insecure practices
  motive: Unknown # Vandalism or attempted deeper compromise
  insertion_phase: source # Modification of source code/package definitions on GitHub
  impact_type: Potential remote execution # If malicious ebuilds were used
  references:
    - https://wiki.gentoo.org/wiki/Github/Incident_Report_2018-06-28
    - https://www.bleepingcomputer.com/news/security/gentoo-linux-github-organization-hacked-repositories-possibly-compromised/
    - https://lwn.net/Articles/758203/
  commits:
    - User: "risacher" # The compromised account used by the attacker
