- name: sendmail
  title: Sendmail official FTP source distribution trojanized (8.12.6)
  synopsis: The official Sendmail FTP server (`ftp.sendmail.org`) was compromised, and the source code tarballs for version 8.12.6 (`.tar.gz` and `.tar.Z` files) were replaced with trojanized versions. The malicious code, reportedly activated during the compilation process, connected to a remote IRC server (port 6667) and potentially allowed remote shell access for the attacker. The compromised files were available for approximately one week.
  start_date: 2002-09-28 # Date compromised files likely appeared on FTP server
  end_date: 2002-10-06 # Date compromise discovered and files replaced
  attribution_type: Unknown # Attacker(s) who breached ftp.sendmail.org
  component_type: Daemon # Mail Transfer Agent
  lang: C # Trojan inserted into C source or build process
  cause: Server compromise # Official FTP distribution server hacked
  motive: Remote access # Backdoor via IRC connection/shell
  insertion_phase: distribution # Official source tarball replaced on distribution FTP site
  impact_type: Backdoor, Remote execution
  references:
    - https://web.archive.org/web/20140720105607/http://www.cert.org/advisories/CA-2002-28.html # Archived CERT Advisory CA-2002-28
    - https://www.theregister.com/2002/10/09/trojanized_sendmail_distro_circulated/ # The Register article (Oct 2002)
    - https://www.exploit-db.com/exploits/21919 # Exploit-DB entry summarizing the incident
    - https://web.archive.org/web/20210515121835/https://www.securityfocus.com/bid/5921/info # Archived SecurityFocus BID 5921
    - https://nvd.nist.gov/vuln/detail/CVE-1999-0661 # CVE grouping historical distribution compromises, lists Sendmail 8.12.6
  domain: ftp.sendmail.org
  domain_type: project host
  artifact_type: Source archive
  versions:
    - 8.12.6 # Specific source tarballs (.tar.gz, .tar.Z)
