- name: phpmyadmin
  title: phpMyAdmin SourceForge mirror distributes backdoored zip file
  repo: https://github.com/phpmyadmin/phpmyadmin
  synopsis: An official download mirror for phpMyAdmin hosted on SourceForge was compromised. Attackers replaced the legitimate `phpMyAdmin-3.5.2.2-all-languages.zip` file with a version containing a backdoor (`server_sync.php`). Users downloading from this specific mirror received the malicious version.
  start_date: 2012-09-25 # Approximate date malicious file appeared
  end_date: 2012-09-27 # Date discovered and removed
  attribution_type: Individual hacker
  component_type: Application # Database management tool
  lang: PHP
  cause: Server compromise # SourceForge mirror infrastructure
  motive: Remote access # Backdoor functionality
  transitive: false
  insertion_phase: distribution # Compromise of official download mirror
  impact_type: Backdoor, Remote execution
  references:
    - https://www.phpmyadmin.net/news/2012/9/27/sourceforge-mirror-compromised/ # Official advisory
    - https://www.zdnet.com/article/phpmyadmin-update-released-after-security-compromise/ # News coverage
  versions:
    - 3.5.2.2 # Specifically the -all-languages.zip file from one mirror
  historical_artifacts:
    - https://sourceforge.net/projects/phpmyadmin/files/phpMyAdmin/3.5.2.2/phpMyAdmin-3.5.2.2-all-languages.zip/download # Original download URL from compromised mirror
    - http://ignum-dl.sourceforge.net/project/phpmyadmin/phpMyAdmin/3.5.2.2/phpMyAdmin-3.5.2.2-all-languages.zip # Specific mirror URL
  current_artifacts:
    - https://www.phpmyadmin.net/news/2012/9/27/sourceforge-mirror-compromised/ # Advisory with technical details
    - https://www.zdnet.com/article/phpmyadmin-update-released-after-security-compromise/ # Analysis with description of the backdoor
  domain: sourceforge.net
  domain_type: package host
  artifact_type: source archive
  hashes:
    - md5:cee5fa3565412733e42a8e461a2bcb39 # Malicious phpMyAdmin-3.5.2.2-all-languages.zip
  clean: true