- name: IPany VPN
  title: South Korean IPany VPN installer backdoored.
  synopsis: The legitimate installer for IPany VPN, a South Korean VPN provider, available on their official website was replaced with a malicious version. This trojanized installer deployed both the legitimate VPN software and the SlowStepper backdoor, used by the PlushDaemon APT group (suspected China-aligned) for espionage.
  start_date: 2024-05-01 # Approximate time malicious installer was detected by ESET (May 2024)
  end_date: 2024-05-31 # Approximate time malicious installer was removed after notification
  attribution_type: Nation-state # (PlushDaemon APT group)
  component_type: Application # (VPN Client)
  lang: Python # (SlowStepper backdoor modules)
  cause: Website compromise # (Vendor website hosting compromised installer)
  motive: Espionage
  transitive: false
  insertion_phase: distribution
  impact_type: Backdoor, Data theft, Remote access
  references:
    - https://www.eset.com/us/about/newsroom/press-releases/eset-discovers-new-china-aligned-apt-group-plushdaemon-and-its-supply-chain-attack-on-south-korean-vpn-service/
    - https://www.bleepingcomputer.com/news/security/hackers-backdoor-south-korean-vpn-installer-with-feature-rich-malware/
    - https://www.welivesecurity.com/en/eset-research/plushdaemon-china-aligned-group-backdoors-south-korean-vpn/ # ESET full technical report
  versions:
    - Specific NSIS installer version available on ipany.co.kr during the compromise period in May 2024.
  historical_artifacts:
    - "Trojanized NSIS installer for IPany VPN, downloaded from ipany.co.kr during May 2024."
  current_artifacts:
    - "https://www.eset.com/us/about/newsroom/press-releases/eset-discovers-new-china-aligned-apt-group-plushdaemon-and-its-supply-chain-attack-on-south-korean-vpn-service/" # ESET Press Release
    - "https://www.welivesecurity.com/en/eset-research/plushdaemon-china-aligned-group-backdoors-south-korean-vpn/" # ESET full technical report (original link from meta.yaml)
  domain: ipany.co.kr # Official vendor website
  domain_type: project download host
  artifact_type: binary archive
  hashes:
    - sha1:33a239a061f8194195125e51e43051594df3e93a # Backdoored NSIS installer for IPany VPN
