- name: unrealircd
  title: UnrealIRCd distribution tarball backdoored for RCE
  synopsis: The official distribution tarball for UnrealIRCd version 3.2.8.1 was replaced with a backdoored version on official download mirrors. The backdoor was hidden within the source code and allowed anyone to execute arbitrary commands with the privileges of the user running the IRC daemon by sending a specific AB;/COMMAND sequence to the server.
  start_date: 2009-11-01 # Approximate date backdoored tarball appeared
  end_date: 2010-06-12 # Date backdoor discovered/announced
  attribution_type: Unknown
  component_type: Daemon # IRC Server
  lang: C # Backdoor code in C source
  cause: Server compromise # Download mirror(s) hacked
  motive: Remote access # Command execution
  insertion_phase: distribution # Official download tarball replaced
  impact_type: Backdoor, Remote execution
  references:
    - https://www.rapid7.com/db/modules/exploit/unix/irc/unreal_ircd_3281_backdoor/ # Exploit module details
  domain: unrealircd.org
  domain_type: project host
  artifact_type: Source archive
  versions:
    - 3.2.8.1 # Specific source tarball Unreal3.2.8.1.tar.gz
  impacted_hashes:
    - e5a4f00a16455005a45d969992173911 # MD5 of backdoored Unreal3.2.8.1.tar.gz
    - 63413f7a8ea69a077a810b588a4b0997 # MD5 of clean Unreal3.2.8.1.tar.gz
