- name: Better MC (Modpack Series)
  title: Better MC modpacks compromised with Fracturiser malware
  synopsis: The CurseForge account for 'Luna Pixel Studios', creators of the very popular 'Better MC' modpack series, was compromised. Attackers uploaded malicious versions of the modpacks (e.g., BMC3 for Forge 1.19.2). These modpacks either directly contained or pulled in dependencies infected with the 'Fracturiser' malware, leading to credential theft (Discord, Microsoft, Minecraft) and further malware propagation on users' systems.
  start_date: 2023-06-01 # Approximate date compromised Luna Pixel Studios account uploaded malicious files
  end_date: 2023-06-08 # Approximate date of widespread discovery and public warnings
  attribution_type: Unknown # Attacker(s) compromising accounts
  component_type: Game # Minecraft Java Edition Modpack
  lang: Java # Modpacks bundle Java mods
  cause: Stolen credentials # Compromised CurseForge account (Luna Pixel Studios)
  motive: Credential theft, Malware propagation
  transitive: false
  historical_artifacts:
    - https://www.curseforge.com/minecraft/modpacks/better-mc-forge/files/4477460 # Potential historical URL for Better MC [Forge] - BMC3 v18
    - https://www.curseforge.com/minecraft/modpacks/better-mc-forge # Original host of compromised modpacks
  current_artifacts:
    - https://github.com/fractureiser-investigation/fractureiser # Main investigation repository
    - https://github.com/clrxbl/NekoClient # Deobfuscated Stage 3 client.jar
    - https://gist.githubusercontent.com/NotNite/79ab1e5501e1ef109e8030059356b1b8/raw/c2102bf5ff74275ac44c2200d5121bfff652fd49/hook.dll.c # Decompiled hook.dll from Stage 3
    - https://gist.github.com/Darkhax/d7f6d1b5bfb51c3c74d3bd1609cab51f # Gist by Darkhax with potentially more affected mods
    - https://hackmd.io/5gqXVri5S4ewZcGaCbsJdQ # Live Stage 3 reversal document
  hashes:
    - sha1:dc43c4685c3f47808ac207d1667cc1eb915b2d82 # Stage 1: dl.jar
    - sha1:52d08736543a240b0cbbbf2da03691ae525bb119 # Stage 2: lib.jar/libWebGL64.jar
    - sha1:6ec85c8112c25abe4a71998eb32480d266408863 # Stage 2: lib.jar/libWebGL64.jar (alt)
    - sha1:c2d0c87a1fe99e3c44a52c48d8bcf65a67b3e9a5 # Stage 3: client.jar
    - sha1:e299bf5a025f5c3fff45d017c3c2f467fa599915 # Stage 3: client.jar (alt)
  domain: curseforge.com
  domain_type: package host
  artifact_type: source archive
  insertion_phase: distribution # Malicious modpack file uploaded to official mod platform
  impact_type: Credential theft, Data theft, Malware infection
  references:
    - https://support.curseforge.com/en/support/solutions/articles/9000228509-june-2023-infected-mods-detection-tool-and-report # CurseForge Advisory listing affected projects (inc. Better MC)
    - https://www.bleepingcomputer.com/news/security/new-fractureiser-malware-used-curseforge-minecraft-mods-to-infect-windows-linux/ # News report confirming Better MC affected
    - https://www.reddit.com/r/feedthebeast/comments/142zxka/some_curseforge_accounts_might_be/ # Community discussion including Luna Pixel Studios/Better MC
    - https://github.com/fractureiser-investigation/fractureiser # Community investigation and detailed analysis (main repo)
    - https://raw.githubusercontent.com/fractureiser-investigation/fractureiser/main/docs/tech.md # Detailed technical breakdown from the investigation
  versions: # Specific versions varied, e.g., Better MC [FORGE] - BMC3 v18, updates pushed around early June 2023 were affected
    - Better MC [Forge] - BMC3 v18
    - Better MC [Forge] - BMC2 v7
    - Better MC [FABRIC] v10 # Potentially other Better MC versions updated via the compromised account
  clean: true
