- name: Better MC (Modpack Series)
  title: Better MC modpacks compromised with Fracturiser malware
  synopsis: The CurseForge account for 'Luna Pixel Studios', creators of the very popular 'Better MC' modpack series, was compromised. Attackers uploaded malicious versions of the modpacks (e.g., BMC3 for Forge 1.19.2). These modpacks either directly contained or pulled in dependencies infected with the 'Fracturiser' malware, leading to credential theft (Discord, Microsoft, Minecraft) and further malware propagation on users' systems.
  start_date: 2023-06-01 # Approximate date compromised Luna Pixel Studios account uploaded malicious files
  end_date: 2023-06-08 # Approximate date of widespread discovery and public warnings
  attribution_type: Unknown # Attacker(s) compromising accounts
  component_type: Modpack # Minecraft Java Edition Modpack
  lang: Java # Modpacks bundle Java mods
  cause: Stolen credentials # Compromised CurseForge account (Luna Pixel Studios)
  motive: Credential theft, Malware propagation
  transitive: false
  domain: curseforge.com
  domain_type: package host
  artifact_type: source archive
  insertion_phase: distribution # Malicious modpack file uploaded to official mod platform
  impact_type: Credential theft, Data theft, Malware infection
  references:
    - https://support.curseforge.com/en/support/solutions/articles/9000228509-june-2023-infected-mods-detection-tool-and-report # CurseForge Advisory listing affected projects (inc. Better MC)
    - https://www.bleepingcomputer.com/news/security/new-fractureiser-malware-used-curseforge-minecraft-mods-to-infect-windows-linux/ # News report confirming Better MC affected
    - https://www.reddit.com/r/feedthebeast/comments/142zxka/some_curseforge_accounts_might_be/ # Community discussion including Luna Pixel Studios/Better MC
  versions: # Specific versions varied, e.g., Better MC [FORGE] - BMC3 v18, updates pushed around early June 2023 were affected
    - Better MC [Forge] - BMC3
    -  # Potentially other Better MC versions updated via the compromised account
