- name: X_TRADER
  title: Trading Technologies X_TRADER software delivered backdoor.
  synopsis: A compromised installer for the retired X_TRADER financial software, available on Trading Technologies' official website and signed with their certificate, contained the VEILEDSIGNAL backdoor. It infected a 3CX employee, initiating a cascading supply chain attack, and reportedly impacted other energy and financial sector organizations.
  start_date: 2021-11-01 # Approximate date compromised signed installer became available
  end_date: 2022-07-26 # Approximate date compromised installer download window ended
  attribution_type: Nation-state
  component_type: application # Financial trading software
  cause: Website compromise # Malicious installer hosted on official site
  motive: Financial gain # Used to gain foothold for further operations
  transitive: false # This was the first stage in the cascading 3CX attack
  insertion_phase: distribution # Compromised installer on official website
  impact_type: Backdoor, Remote access # Enabled credential theft and lateral movement
  impact_user_count: 97 # Reported number of downloads of the compromised package
  references:
    - https://cloud.google.com/blog/topics/threat-intelligence/3cx-software-supply-chain-compromise # Mandiant report detailing the link
    - https://www.securityweek.com/cascading-supply-chain-attack-3cx-hacked-after-employee-downloaded-trojanized-app/
    - https://www.cybersecuritydive.com/news/3cx-x-trader-symantec-supply-chain/648414/
    - https://www.zetter-zeroday.com/software-maker-3cx-was-compromised/
  versions:
    - "Specific X_TRADER installer versions available Nov 2021 - July 2022 (e.g., X_TRADER_r7.17.90p608.exe)"
  domain: tradingtechnologies.com
  domain_type: project host
  artifact_type: binary archive # Software installer
  historical_artifacts:
    - "https://tradingtechnologies.com/x-trader/downloads/X_TRADER_r7.17.90p608.exe"
    - "https://www.tradingtechnologies.com/legacy-downloads/X_TRADER%20Pro%207.17.10.exe"
    - "https://downloads.tradingtechnologies.com/trading-software/x-trader/legacy/setup.exe"
  current_artifacts:
    - "https://www.virustotal.com/gui/file/ef4ab22e565684424b4142b1294f1f4d"
    - "https://github.com/sophoslabs/IoCs/blob/master/TradingTech-IoCs.csv"
    - "https://www.mandiant.com/resources/blog/trading-in-the-dark"
  commits:
  hashes:
    - md5:ef4ab22e565684424b4142b1294f1f4d # MD5 hash for one known malicious installer Setup.exe within the package
    - sha256:88968c9f1de3c41c54a025a0f51a818c1a0b0c98e7affe0ea0aa0ad6e441fc46 # Malicious X_TRADER installer
    - sha256:8c9395a019def2cc80a0320a1285ccc4cb1cd73ecb89886a1c03da5aaf5db0a3 # VEILEDSIGNAL backdoor
