- name: openx
  title: OpenX ad server downloads compromised serving malware
  synopsis: The infrastructure serving downloads and updates for the OpenX Source ad server software was compromised. Attackers modified official software packages to include malicious code. This code redirected website visitors viewing ads served by compromised OpenX servers to the Styx exploit kit, infecting end-users.
  start_date: 2013-08-01 # Approximate start, active through Nov/Dec
  end_date: 2013-12-06 # Public disclosure and cleanup period
  attribution_type: Cybercriminal gang # Likely financially motivated group
  component_type: Application # Ad Server
  lang: PHP # Malicious code inserted into PHP application
  cause: Server compromise # Download/update infrastructure breached
  motive: Financial gain # Exploit kit distribution
  transitive: false
  insertion_phase: distribution # Compromise of official download/update mechanism
  impact_type: Malware distribution, Remote execution # Via exploit kit
  references:
    - https://blog.sucuri.net/2013/12/openx-compromise-serving-malware.html # Original disclosure
    - https://www.theregister.com/2013/12/05/openx_hack_malware_serving/ # News coverage
    - https://www.zdnet.com/article/openx-ad-software-compromised-to-serve-malware-styx-exploit-kit/ # Additional coverage
  versions:
    - "OpenX Source 2.8.10" # At least this version confirmed affected
  historical_artifacts:
    - https://www.openx.org/download/openx-source-2.8.10.zip # Original download URL (inactive)
    - https://web.archive.org/web/20131201000000*/http://www.openx.org/download/openx-source-2.8.10.zip # Archive snapshot
  current_artifacts:
    - https://blog.sucuri.net/2013/12/openx-compromise-serving-malware.html # Analysis with details
    - https://www.unmaskparasites.com/2013/12/05/ad-networks-openx-source-compromised/ # Technical analysis with code snippets
  domain: openx.com
  domain_type: project download host
  artifact_type: source archive
  hashes:
    - md5:3cf59a7b8996dcc52370cf918f248ee4 # Reported hash of compromised file
