- name: transmission
  title: Transmission macOS installer distributed KeRanger ransomware
  repo: https://github.com/transmission/transmission
  synopsis: The official website for the Transmission BitTorrent client was compromised. Attackers replaced the legitimate macOS installer for version 2.90 with a malicious disk image containing the OSX.KeRanger ransomware. Users downloading and installing this version had their files encrypted.
  start_date: 2016-03-04
  end_date: 2016-03-06 # Approximate window file was available
  attribution_type: Cybercriminal Gang
  component_type: Application
  lang: Binary # Ransomware embedded in DMG
  cause: Compromised Infrastructure # Website/download server hacked
  motive: Financial Gain # Ransomware
  transitive: false
  insertion_phase: distribution # Official download file replaced
  impact_type: Financial Exploitation
  references:
    - https://www.paloaltonetworks.com/blog/2016/03/new-os-x-ransomware-keranger-infected-transmission-bittorrent-client-installer/
    - https://securelist.com/osxkeranger-ransomware-infecting-transmission-users/74214/
  versions:
    - 2.90 # Specific macOS DMG installer
  historical_artifacts:
    - https://download.transmissionbt.com/files/Transmission-2.90.dmg # Original compromised download location
    - https://updates.transmissionbt.com/Transmission-2.90.dmg # Alternate download path potentially affected
  current_artifacts:
    - https://www.paloaltonetworks.com/blog/2016/03/new-os-x-ransomware-keranger-infected-transmission-bittorrent-client-installer/ # Analysis with technical details
    - https://securelist.com/osxkeranger-ransomware-infecting-transmission-users/74214/ # Kaspersky analysis with screenshots
    - https://www.welivesecurity.com/2016/03/07/new-mac-ransomware-appears-keranger-spread-via-transmission-app/ # Additional technical details
  domain: transmissionbt.com
  domain_type: project download host
  artifact_type: binary archive
  hashes:
    - sha256:7552f29459368037868f5b7cf09884080831079276a4647682a8aac86e0b95e7 # Malicious Transmission-2.90.dmg
    - sha256:2eef2cf8a39e98e91b09d24602c662598f39b449aa9b5f3ac6ea19690033a3c1 # KeRanger malware component (General.rtf)
