- name: Adups
  title: Adups firmware update component spied on users.
  synopsis: Firmware-Over-The-Air (FOTA) update software from Shanghai Adups Technology Co., pre-installed by various OEMs on millions of Android devices (including budget US models like BLU), covertly collected and transmitted extensive PII (texts, call logs, contacts, location, app usage) to servers in China without user consent. Adups claimed this was designed for Chinese manufacturers and mistakenly included on international devices.
  start_date: Unknown # Activity ongoing before discovery
  end_date: 2016-11-16 # Approximate date Adups pushed update to disable PII collection on affected US models after public disclosure
  attribution_type: Commercial company # Shanghai Adups Technology Co.
  component_type: firmware # System application (FOTA client)
  cause: Vendor deliberate inclusion # Code included by Adups, integrated by OEMs
  motive: Data collection # Stated purpose by Adups was analytics for Chinese OEMs; privacy implications severe
  transitive: false
  insertion_phase: dependency # Adups component integrated into OEM firmware builds
  impact_type: Spyware, Data theft
  impact_user_count: 700000000 # Adups claimed presence on 700M devices globally; specific impact numbers vary
  references:
    - https://www.kryptowire.com/adups-technical-report # Original Kryptowire findings (may require access)
    - https://www.nytimes.com/2016/11/16/us/politics/china-phones-software-security.html
    - https://thehackernews.com/2016/11/hacking-android-smartphone.html
    - https://android.gadgethacks.com/news/these-android-phones-could-be-affected-by-adups-chinese-spyware-0175014/
  versions:
    - "Adups FOTA client versions ~5.0.x - 5.3.x on various Android devices (e.g., BLU R1 HD, others)"
  artifacts:
    - "System applications: com.adups.fota, com.adups.fota.sysoper"
  domain: Various Android OEMs # e.g., BLU Products, potentially Huawei, ZTE (though they denied use in US models)
  domain_type: project host # OEM level integration
  artifact_type: hardware # Shipped with device firmware
