- name: EvLog
  title: Altair EvLog update delivered Kingslayer malware.
  synopsis: Attackers compromised update mechanisms for Altair Technologies' EvLog event log management software. Altered versions, signed with a stolen private key, were distributed containing the 'Kingslayer' malware which provided backdoor access, targeting telecom and military organizations primarily between April and July 2015.
  start_date: 2015-04-01 # Approximate start of infection window
  end_date: 2015-07-31 # Approximate end of infection window
  attribution_type: Unknown attacker # Described as sophisticated
  component_type: application # Event log management tool
  cause: Stolen certificates/keys # Used to sign malicious updates
  motive: Espionage # Inferred from targeted sectors
  transitive: false
  insertion_phase: distribution # Malicious update distributed via compromised channel
  impact_type: Backdoor, Remote access, Credential theft
  impact_user_count: 100 # Estimate based on report mentioning 4 telcos, 10+ military orgs
  references:
    - https://web.archive.org/web/20170726040823/https://www.comsecglobal.com/kingslayer-a-supply-chain-attack/ # Archived Comsec Global report (Primary analysis with IOCs)
    - https://securityaffairs.com/58864/cyber-crime/operation-wilysupply-hacking.html # Contextual mention of Altair/EvLog
  versions:
    - "EvLog versions updated between April-July 2015"
  historical_artifacts:
    - "Compromised EvLog update packages distributed via Altair Technologies' official update channels."
  current_artifacts:
    - "https://web.archive.org/web/20170726040823/https://www.comsecglobal.com/kingslayer-a-supply-chain-attack/" # Archived Comsec Global report detailing the attack and IOCs
  hashes:
    - sha256:caea901a301b9c103d90b8539819e050e57b67c6ff4d7863ad1cd549f5fdc2af # Malicious file (Comsec report)
    - sha256:383d60bffd5dc64e38893361cb03939bc8c6d5e476dc70755eb0886947e51661 # Malicious file (Comsec report)
    - sha256:7aa474d0d39a41768149f413c451e9208f73af4d262b6575ada31644f5699153 # Malicious file (Comsec report)
    - sha256:15113f237b29f51c78f315db7d815c5ed1340f52b500f66979edb153515910d7 # Malicious file (Comsec report)
    - sha256:72ccf28f4636403249d87721e802140ccae2248b810860f8c5d4f33d07363597 # Malicious file (Comsec report)
    - sha256:4286ecd104cf0667064ad008e5ac9ffa33a0f7858bb745d533fdb30369e89dd4 # Malicious file (Comsec report)
  domain: altairtech.com # Likely original vendor domain
  domain_type: project download host
  artifact_type: binary archive # Software update
