- name: ircII
  title: ircII FTP distribution backdoored for remote access
  synopsis: The official FTP server (ftp.irc.org) hosting the ircII source code was compromised. The `ircii-2.8.2.tar.gz` distribution was modified; specifically, the file `ircd/s_bsd.c` had a backdoor inserted. This backdoor connected to IP 198.168.253.139 on TCP port 30000 and attempted to start an interactive shell (`/bin/sh -i`), allowing remote access with the privileges of the user running ircII.
  start_date: 1998-10-22 # Approximate date compromised tarball appeared
  end_date: 1999-01-21 # Date backdoor was publicly discovered
  attribution_type: Individual hacker
  component_type: Application
  lang: C # Backdoor code inserted into C source
  cause: Server compromise # FTP server hacked
  motive: Remote access
  transitive: false
  insertion_phase: distribution # Official FTP site compromised
  impact_type: Backdoor, Remote execution
  references:
    - https://www.cert.org/historical/advisories/CA-1999-01.cfm # CERT Advisory CA-1999-01 (covers this incident)
    - https://web.archive.org/web/20091027105544/http://geocrawler.com/archives/3/55/1998/10/0/2177558/ # Mailing list post during discovery
  versions:
    - 2.8.2 # Specific source tarball
  historical_artifacts:
    - ftp://ftp.irc.org/irc/clients/ircii-2.8.2.tar.gz # Original compromised download location
    - ftp://ftp.undernet.org/pub/irc/clients/unix/ircII/ircii-2.8.2.tar.gz # Mirror potentially affected
  current_artifacts:
    - https://web.archive.org/web/20140720105610/http://www.cert.org/advisories/CA-1999-01.html # Archive of advisory with technical details
    - https://attrition.org/security/advisory/fedcirc/1999/fedcirc.99.01.txt # Advisory with backdoor explanation
  domain: ftp.irc.org
  domain_type: project download host
  artifact_type: source archive
  hashes:
    - md5:a2eadc5d2e01fceb4c5728e85a28f2dd # Backdoored ircii-2.8.2.tar.gz
    - md5:f3c149e1e239263731e0f75730121eb0 # Legitimate ircii-2.8.2.tar.gz
