- name: exotel
  title: exotel PyPI package compromised via phishing.
  repo: https://github.com/exotel/exotel-python
  synopsis: The PyPI account for the 'exotel' package maintainer was compromised via a phishing campaign ("JuiceLedger"). Attackers then uploaded a malicious version (0.1.6) containing code to download and execute an infostealer malware payload on users' systems during installation.
  start_date: 2022-08-01 # Approximate start of campaign/compromise window
  end_date: 2022-08-31 # Approximate discovery/remediation window
  attribution_type: Threat Actor # (JuiceLedger)
  component_type: Library
  lang: Python # Malicious code added to package
  cause: Phishing, Stolen credentials
  motive: Credential theft, Data theft
  transitive: false
  insertion_phase: distribution # Malicious version uploaded to package host
  impact_type: Infostealer, Credential theft
  impact_user_count: 480000 # Approximate total downloads for the package historically, indicating potential reach
  references:
    - https://checkmarx.com/blog/first-known-phishing-attack-against-pypi-users/
    - https://www.sentinelone.com/labs/pypi-phishing-campaign-juiceledger-threat-actor-pivots-from-fake-apps-to-supply-chain-attacks/
    - https://www.itpro.com/security/phishing/368899/pypi-packages-succumb-to-mailchimp-phishing-scam
  versions:
    - 0.1.6
  historical_artifacts:
    - https://pypi.org/project/exotel/0.1.6/ # URL of the compromised version (now removed)
    - https://files.pythonhosted.org/packages/00/11/8be2e89e8e27dcd7fb53ea71c47a4bf99c5bec48c8d4ab7d6eeb1fc47c3/exotel-0.1.6.tar.gz # Direct package URL
  current_artifacts:
    - https://checkmarx.com/blog/first-known-phishing-attack-against-pypi-users/ # Analysis with code sample
    - https://www.sentinelone.com/labs/pypi-phishing-campaign-juiceledger-threat-actor-pivots-from-fake-apps-to-supply-chain-attacks/ # Technical analysis with screenshots
  domain: pypi.org
  domain_type: package host
  artifact_type: source archive
  hashes:
    - sha256:fbb13333b05eaab13d5d4810f92dbd5dfc4c25cf14e4471c6352b046c6653b6f # exotel-0.1.6.tar.gz
    - sha256:60434af3ebe924efabc96558e6c8d8176bf4eb06dd6cc47b4c491da9964be874 # python-install.scr (payload downloaded by exotel 0.1.6)
    - sha256:8e97c6883e7af5cc1f88ac03197d62298906ac4a35a789d94cc9fde45ee7ea13 # LedgerSetup.scr (related JuiceLedger campaign payload)
