- name: exotel
  title: exotel PyPI package compromised via phishing.
  synopsis: The PyPI account for the 'exotel' package maintainer was compromised via a phishing campaign ("JuiceLedger"). Attackers then uploaded a malicious version (0.1.6) containing code to download and execute an infostealer malware payload on users' systems during installation.
  start_date: 2022-08-01 # Approximate start of campaign/compromise window
  end_date: 2022-08-31 # Approximate discovery/remediation window
  attribution_type: Threat Actor # (JuiceLedger)
  component_type: Library
  lang: Python # Malicious code added to package
  cause: Phishing, Stolen credentials
  motive: Credential theft, Data theft
  transitive: false
  insertion_phase: distribution # Malicious version uploaded to package host
  impact_type: Infostealer, Credential theft
  impact_user_count: 480000 # Approximate total downloads for the package historically, indicating potential reach
  references:
    - https://checkmarx.com/blog/first-known-phishing-attack-against-pypi-users/
    - https://www.sentinelone.com/labs/pypi-phishing-campaign-juiceledger-threat-actor-pivots-from-fake-apps-to-supply-chain-attacks/
    - https://www.itpro.com/security/phishing/368899/pypi-packages-succumb-to-mailchimp-phishing-scam
  versions:
    - 0.1.6
  artifacts:
    - https://pypi.org/project/exotel/0.1.6/ # URL of the compromised version (now removed)
  domain: pypi.org
  domain_type: package host
  artifact_type: source archive
