- name: "Point Blank"
  title: "Point Blank game executable backdoored via supply chain"
  synopsis: "Linked to the ShadowHammer/BARIUM APT group (also involved in the ASUS attack), the executable for the online game Point Blank was reportedly recompiled with malicious code sometime before 2019. This supply chain compromise likely aimed to collect system information from players. The compromised executables were signed with legitimate digital certificates."
  attribution_type: Nation-state
  component_type: game
  cause: "Build system compromise"
  motive: Espionage # Data collection (system info, MAC addresses)
  transitive: false
  insertion_phase: CI/CD # Malicious code injected during build process
  impact_type: Data theft
  references:
    - https://malwaretips.com/threads/point-blank-gamers-targeted-with-backdoor-malware.92107/
    - https://threatpost.com/gamers-pointblank-backdoor-malware/144088/
    - https://securelist.com/operation-shadowhammer/89083/ # Kaspersky report on ShadowHammer
    - https://www.bankinfosecurity.com/shadowhammer-spreads-across-online-gaming-supply-chain-a-12409 # Discusses ShadowHammer targeting gaming suppliers
    - https://www.welivesecurity.com/2019/03/11/gaming-industry-scope-attackers-asia/
  versions:
    - "Unknown specific game executable versions/patches for Point Blank"
  historical_artifacts:
    - "Compromised Point Blank game executables distributed via official game patches or downloads, potentially through platforms like Steam or direct publisher websites, prior to 2019."
  current_artifacts:
    - "https://securelist.com/operation-shadowhammer/89083/" # Kaspersky report on ShadowHammer, which mentions gaming industry targets
    - "https://www.bankinfosecurity.com/shadowhammer-spreads-across-online-gaming-supply-chain-a-12409" # Discusses ShadowHammer targeting gaming suppliers
  domain: "Official game websites/distributors (e.g., Zepetto Co. for Point Blank)"
  domain_type: package host # Or project download host
  artifact_type: binary archive # Game client/patch
  date_occurred: "Before 2019"
  actor_country: China # BARIUM APT group
  target_country: Asia # Primarily Thailand
  actor_name: "BARIUM (APT17, Axiom, Deputy Dog)"
