- name: MB Connect Line
  title: MB Connect Line installer distributed Havex.
  synopsis: As part of the DragonFly/Energetic Bear campaign, MB Connect Line, a German vendor of industrial routers and remote access solutions, had a software installer on their website trojanized with the Havex Remote Access Trojan (RAT). This allowed attackers to gain a foothold in networks of organizations that downloaded and installed the compromised software.
  start_date: 2013-01-01 # Approximate start of wider Havex campaign with trojanized installers
  end_date: 2014-06-01 # Public disclosure and remediation period for the campaign
  attribution_type: Nation-state # (DragonFly/Energetic Bear)
  component_type: Application # (Remote access software/utility)
  lang: C++ # (Havex RAT)
  cause: Website compromise # (Vendor website)
  motive: Espionage, Network reconnaissance
  transitive: false
  insertion_phase: distribution
  impact_type: Backdoor, Data theft, Remote access
  references:
    - https://securityledger.com/2014/07/industrial-control-vendors-identified-in-dragonfly-attack/
    - https://www.cisa.gov/news-events/ics-alerts/ics-alert-14-176-02a
  versions:
    - Specific software installers available for download from their website during the compromise period.
  domain: mbconnectline.com # (Official vendor website)
  domain_type: project host
  artifact_type: binary archive
