- name: MB Connect Line
  title: MB Connect Line installer distributed Havex.
  synopsis: As part of the DragonFly/Energetic Bear campaign, MB Connect Line, a German vendor of industrial routers and remote access solutions, had a software installer on their website trojanized with the Havex Remote Access Trojan (RAT). This allowed attackers to gain a foothold in networks of organizations that downloaded and installed the compromised software.
  start_date: 2013-01-01 # Approximate start of wider Havex campaign with trojanized installers
  end_date: 2014-06-01 # Public disclosure and remediation period for the campaign
  attribution_type: Nation-state # (DragonFly/Energetic Bear)
  component_type: Application # (Remote access software/utility)
  lang: C++ # (Havex RAT)
  cause: Website compromise # (Vendor website)
  motive: Espionage, Network reconnaissance
  transitive: false
  insertion_phase: distribution
  impact_type: Backdoor, Data theft, Remote access
  references:
    - https://securityledger.com/2014/07/industrial-control-vendors-identified-in-dragonfly-attack/
    - https://www.cisa.gov/news-events/ics-alerts/ics-alert-14-176-02a
    - https://web.archive.org/web/20190717022917/https://www.symantec.com/content/en/us/enterprise/media/security_response/whitepapers/dragonfly-threat-against-energy-sector-systems.pdf # Symantec Dragonfly report
  versions:
    - Specific software installers available for download from their website during the compromise period.
  domain: mbconnectline.com # (Official vendor website)
  domain_type: project download host
  artifact_type: binary archive
  historical_artifacts:
    - "Trojanized MB Connect Line software installer (e.g., for mbCHECK, mbCONF), downloaded from mbconnectline.com during 2013-2014."
  current_artifacts:
    - "https://web.archive.org/web/20190717022917/https://www.symantec.com/content/en/us/enterprise/media/security_response/whitepapers/dragonfly-threat-against-energy-sector-systems.pdf" # Symantec Dragonfly report with IOCs
    - "https://www.cisa.gov/news-events/ics-alerts/ics-alert-14-176-02a" # CISA Alert on Havex/Dragonfly campaign, lists compromised vendor software
    - "https://www.f-secure.com/documents/996508/1030745/Threat_Intelligence_Report_Havex_an_Energetic_Bear_Targets_ICS_SCADA.pdf" # F-Secure Havex report with IOCs (General Havex reference)
    - "https://www.virustotal.com/gui/file/09a35ac2f7f9ca156c3a2ab2466c029976535390099101632e904a7ca3f6764d" # Example Havex RAT sample (SHA256)
  hashes:
    - sha256:09a35ac2f7f9ca156c3a2ab2466c029976535390099101632e904a7ca3f6764d # Havex RAT (Oldrea) payload
    - sha256:4a1a783a11c1a2a9d5915717b16ebb5012c685f4457a08246666d7d2f7dcb238 # Another common Havex RAT sample
    - md5:f691c8f16e290f829710ff0a18ff2532 # Havex component (client.dll)
