- name: ctx
  title: ctx NPM package maintainer hijack steals credentials
  repo: https://github.com/rreverser/ctx
  synopsis: Attacker gained access to the maintainer's account for 'ctx', a utility library. They published a malicious version designed to steal environment variables and `.npmrc` credentials upon installation. The malicious code was hidden in a test file.
  start_date: 2022-05-18 # Approximately when the malicious version was published
  end_date: 2022-05-18 # Malicious version quickly removed
  attribution_type: Individual Hacker
  component_type: Library
  lang: Javascript
  cause: Compromised Account/Credentials
  motive: Credential Theft
  transitive: false
  historical_artifacts:
    - https://registry.npmjs.org/ctx/-/ctx-0.1.2.tgz
  current_artifacts:
    - https://socket.dev/npm/package/ctx/versions # Historical version information
    - https://thehackernews.com/2022/05/pypi-package-ctx-and-php-library-phpass.html # News report covering ctx and phpass
  domain: npmjs.org
  domain_type: package host
  artifact_type: source archive
  insertion_phase: distribution
  impact_type: Data Exfiltration
  references:
    - https://thehackernews.com/2022/05/pypi-package-ctx-and-php-library-phpass.html # News report covering ctx and phpass
  versions:
    - 0.1.2
  hashes:
    - sha256:195f077e7e3390951309a5e8fa0f02f16110d41915fc569097e6c90dfb76755e # ctx-0.1.2.tgz
