- name: ctx
  title: ctx NPM package maintainer hijack steals credentials
  synopsis: Attacker gained access to the maintainer's account for 'ctx', a utility library. They published a malicious version designed to steal environment variables and `.npmrc` credentials upon installation. The malicious code was hidden in a test file.
  start_date: 2022-05-18 # Approximately when the malicious version was published
  end_date: 2022-05-18 # Malicious version quickly removed
  attribution_type: Individual hacker
  component_type: Library
  lang: Javascript
  cause: Stolen credentials
  motive: Credential theft
  insertion_phase: distribution
  impact_type: Credential theft
  references:
    - https://github.com/advisories/GHSA-2qrg-x2p9-54g6
    - https://security.snyk.io/vuln/SNYK-JS-CTX-2832062
    - https://www.bleepingcomputer.com/news/security/npm-package-ctx-hijacked-to-steal-developer-aws-keys-env-vars/
  versions:
    - 0.1.2
  impacted_hashes:
    - 195f077e7e3390951309a5e8fa0f02f16110d41915fc569097e6c90dfb76755e # phpass-0.1.2.tgz
