- name: phpMyAdmin
  title: phpMyAdmin compromised download mirror
  start_date: 2009-09-25
  end_date: 2009-09-25
  license: GPL
  website: https://www.phpmyadmin.net/
  repo: https://github.com/phpmyadmin/phpmyadmin
  attribution_type: unknown
  component_type: Application
  lang: PHP
  cause: compromise
  motive: backdoor
  attack_vector: mirror compromise
  insertion_phase: distribution
  impact_type: backdoor
  impact_user_count: 2000
  references:
    - https://www.phpmyadmin.net/security/PMASA-2009-5/
  versions:
    - 3.2.2
  synopsis: A download mirror for phpMyAdmin was compromised, with backdoored versions made available for download. The compromised versions contained a backdoor that allowed remote code execution.
  compromise_desc: Unknown attackers compromised the SourceForge mirror hosting phpMyAdmin and replaced legitimate downloads with backdoored versions. The backdoor was discovered when users reported suspicious behavior in their phpMyAdmin installations.
  impact_desc: The backdoor allowed attackers to execute arbitrary PHP code on web servers running the compromised version. The phpMyAdmin team quickly issued an advisory warning users to verify the integrity of their downloads and to reinstall from official sources.
