- name: spam
  title: spam PyPI package compromised via phishing.
  synopsis: Similar to the 'exotel' incident during the same phishing campaign ("JuiceLedger"), the maintainer account for a PyPI package named 'spam' was compromised. Malicious versions (2.0.2, 4.0.2) were uploaded, designed to download and execute infostealer malware upon installation.
  start_date: 2022-08-01 # Approximate start of campaign/compromise window
  end_date: 2022-08-31 # Approximate discovery/remediation window
  attribution_type: Threat Actor # (JuiceLedger)
  component_type: Library
  lang: Python # Malicious code added to package
  cause: Phishing, Stolen credentials
  motive: Credential theft, Data theft
  transitive: false
  insertion_phase: distribution # Malicious version uploaded to package host
  impact_type: Infostealer, Credential theft
  impact_user_count: 200000 # Approximate total downloads for the package historically, indicating potential reach
  references:
    - https://checkmarx.com/blog/first-known-phishing-attack-against-pypi-users/
    - https://www.sentinelone.com/labs/pypi-phishing-campaign-juiceledger-threat-actor-pivots-from-fake-apps-to-supply-chain-attacks/
    - https://www.itpro.com/security/phishing/368899/pypi-packages-succumb-to-mailchimp-phishing-scam
  versions:
    - 2.0.2
    - 4.0.2
  historical_artifacts:
    - https://pypi.org/project/spam/ # Original package location
    - pkg:pypi/spam@2.0.2 # Compromised version
    - pkg:pypi/spam@4.0.2 # Compromised version
  current_artifacts:
    - https://checkmarx.com/blog/first-known-phishing-attack-against-pypi-users/ # Analysis and IOCs for JuiceLedger campaign
    - https://www.virustotal.com/gui/file/60434af3ebe924efabc96558e6c8d8176bf4eb06dd6cc47b4c491da9964be874 # VirusTotal entry for python-install.scr payload
  hashes:
    - sha256:60434af3ebe924efabc96558e6c8d8176bf4eb06dd6cc47b4c491da9964be874 # python-install.scr (payload downloaded by malicious spam package versions)
  domain: pypi.org
  domain_type: package host
  artifact_type: source archive
