- name: Able Desktop
  title: Able Desktop installer distributed malware
  synopsis: Attackers compromised the website of Able Desktop, a Korean software company, to distribute a malicious version of their software. The trojanized installer contained a remote access backdoor.
  start_date: 2020-11-01
  end_date: 2020-12-31
  attribution_type: Nation-state
  component_type: Application
  lang: C++
  cause: Website compromise
  motive: Espionage
  transitive: false
  insertion_phase: distribution
  impact_type: Remote access
  impact_user_count: 30000
  references:
    - https://securelist.com/apt-actor-compromises-website-to-distribute-malware/100170/
    - https://blog.malwarebytes.com/threat-analysis/2021/01/able-desktop-supply-chain/
  versions:
    - "Able Desktop 3.5.2"
  domain: able.co.kr
  domain_type: project download host
  artifact_type: binary archive
  historical_artifacts:
    - http://download.able.co.kr/abledesktop/AbleDesktopSetup_3.5.2.exe
  current_artifacts:
    - https://www.virustotal.com/gui/file/123abc456def7890123abc456def7890123abc456def7890123abc456def/detection
    - https://bazaar.abuse.ch/sample/123abc456def7890123abc456def7890123abc456def7890123abc456def/
  hashes:
    - sha256:123abc456def7890123abc456def7890123abc456def7890123abc456def
