- name: British Airways (via Modernizr script)
  title: British Airways breached via modified script.
  synopsis: British Airways' website was compromised by attackers who modified a JavaScript library, Modernizr, that was loaded on their payment pages. This malicious script captured and exfiltrated customer names, addresses, payment card details, and login credentials. While Modernizr is an open-source library, its modification on BA's site as part of their supplied code to users represents a compromise of a component in their web delivery supply chain.
  start_date: 2018-08-21
  end_date: 2018-09-05
  attribution_type: Cybercriminal gang # (Magecart)
  component_type: Library # (JavaScript library used by the website)
  lang: JavaScript
  cause: Website compromise # (Compromise of script on BA servers)
  motive: Financial gain
  transitive: false # Attack was on BA's direct asset/script delivery
  insertion_phase: distribution # (Compromised script served from BA infrastructure)
  impact_type: Credential theft, Data theft
  impact_user_count: 380000 # Approximate number of payment cards affected
  references:
    - https://www.riskiq.com/blog/labs/magecart-british-airways-breach/
    - https://www.britishtrust.com/information-commissioner-statement-on-british-airways/ # (Mentions ICO investigation)
  versions:
    - The specific version of Modernizr.js and related scripts served by British Airways during the incident window.
  domain: ba.com
  domain_type: project host
  artifact_type: source archive # (JavaScript file)
  historical_artifacts:
    - "https://www.britishairways.com/scripts/modernizr.js" # The compromised Modernizr script path (speculative, based on common practice)
  current_artifacts:
    - "https://www.riskiq.com/blog/labs/magecart-british-airways-breach/" # Contains analysis and code snippets of the modified script
