- name: "OpenSSH-portable"
  title: "OpenSSH source compromised with backdoor"
  start_date: 2002-07-30
  end_date: 2002-08-01
  license: "BSD"
  website: "https://www.openssh.com/"
  repo: "https://github.com/openssh/openssh-portable"
  attribution_type: "unknown"
  component_type: "Application"
  lang: "C"
  cause: "compromise"
  motive: "backdoor"
  attack_vector: "distribution server"
  insertion_phase: "distribution"
  impact_type: "backdoor"
  references:
    - "https://www.theregister.com/2002/08/01/openssh_backdoore
