- name: agama
  title: Agama wallet compromised via malicious dependency backdoor
  synopsis: The Agama cryptocurrency wallet application inadvertently included a compromised version of the `electron-native-notify` NPM package (v1.1.6) as a dependency in its builds. This resulted in official Agama wallet releases containing a backdoor (reverse shell) inherited from the dependency, potentially allowing attackers remote access and theft of wallet seeds or private keys.
  start_date: 2018-08-01 # Approximate date malicious dependency published/included in Agama builds
  end_date: 2018-08-13 # Date Komodo Platform issued warnings and advised updates
  attribution_type: Unknown # Same attribution as the electron-native-notify compromise
  component_type: Application # Cryptocurrency Wallet
  lang: Javascript # Wallet primarily JS/Electron; backdoor was JS
  cause: Dependency compromise # Malicious electron-native-notify included
  motive: Financial gain # Cryptocurrency theft
  transitive: true
  insertion_phase: dependency # Compromised dependency pulled during application build
  impact_type: Backdoor, Remote access, Credential theft # Wallet seeds/keys
  references:
    - https://blog.npmjs.org/post/176971882940/vulnerability-in-agamas-komodo-wallet # NPM blog post specifically about the Agama impact
    - https://web.archive.org/web/20180817161006/https://komodoplatform.com/agama-vulnerability-update/ # Archived Komodo Platform vulnerability update on Agama
    - https://medium.com/intrinsic/compromised-npm-package-electron-native-notify-28c753f6b8c3 # Original report often mentioning Agama as affected
  versions:
    - 0.3.3 # Versions confirmed affected by Komodo advisory
    - 0.3.4 # Versions confirmed affected by Komodo advisory
    # Potentially other versions built using the compromised dependency during its availability
