- name: IBM Aptiva
  title: IBM Aptiva PCs shipped pre-infected with CIH virus.
  synopsis: In early 1999, IBM accidentally shipped several thousand Aptiva consumer PCs pre-installed with the destructive CIH (Chernobyl) file virus. The contamination occurred during manufacturing due to an infected test diskette and outdated antivirus software on a duplication server, shortly before the virus's damaging payload activation date (April 26th).
  start_date: 1999-03-05 # Manufacturing start date for affected batch
  end_date: 1999-03-17 # Manufacturing end date for affected batch (Disclosed April 1999)
  attribution_type: Accidental
  component_type: hardware # Virus pre-installed on PC hard drive
  cause: Manufacturing error # Contamination during OS/software pre-installation
  motive: Not applicable # Accidental
  transitive: false
  insertion_phase: distribution # Occurred during OEM pre-installation/manufacturing
  impact_type: Data destruction, Hardware damage (BIOS payload)
  impact_user_count: 5000 # "Several thousand" estimated affected PCs shipped
  references:
    - https://web.archive.org/web/20000818190934/http://www.zdnet.com/zdnn/stories/news/0,4586,2236884,00.html # Archived ZDNet article
    - https://en.wikipedia.org/wiki/CIH_(computer_virus)#Incidents
    - https://www.f-secure.com/v-descs/cih.shtml # Mentions IBM Aptiva incident
  versions:
    - "IBM Aptiva models 240, 301, 520, 580 manufactured March 5-17, 1999"
  historical_artifacts:
    - "IBM Aptiva consumer PCs (models 240, 301, 520, 580) manufactured between March 5 and March 17, 1999, shipped with pre-installed CIH virus."
  current_artifacts:
    - "https://www.f-secure.com/v-descs/cih.shtml" # F-Secure analysis of CIH virus, mentions IBM incident
    - "https://web.archive.org/web/20000818190934/http://www.zdnet.com/zdnn/stories/news/0,4586,2236884,00.html" # ZDNet news article on the incident
    - "https://www.virustotal.com/gui/file/5f778e1f90c67968a95874380a19198f7a0a860f9521935096c6bf46905f79a9" # Example CIH v1.2 (W95.CIH.1003) sample on VirusTotal
    - "https://www.virustotal.com/gui/file/c8b72931950b2006a96878e0a39728f725db5d4e8e62e6df2a292ae096721a89" # Example CIH v1.4 (W95.CIH.1019) sample on VirusTotal
  hashes:
    - md5:2b3762908955147287db7f377d66976b # W95/CIH.1003 (CIH v1.2)
    - md5:7b8a3132f23f2300710631017e3f0d2f # W95/CIH.1019 (CIH v1.4)
    - sha256:5f778e1f90c67968a95874380a19198f7a0a860f9521935096c6bf46905f79a9 # CIH v1.2 (W95.CIH.1003)
    - sha256:c8b72931950b2006a96878e0a39728f725db5d4e8e62e6df2a292ae096721a89 # CIH v1.4 (W95.CIH.1019)
  domain: ibm.com
  domain_type: project host
  artifact_type: hardware # Shipped with device
