- name: Conceptworld
  title: Conceptworld installers trojanized, data theft.
  synopsis: Installers for Notezilla, RecentX, and Copywhiz, from conceptworld.com, were compromised. Trojanized installers executed malware stealing browser credentials, crypto wallets, clipboard/keystrokes, and downloading more payloads. Rapid7 discovered the compromise, and Conceptworld remediated it within 12 hours of disclosure.
  start_date: 2024-06-07
  end_date: 2024-06-24
  component_type: application
  lang: Python
  motive: Financial gain, Data theft
  transitive: false
  insertion_phase: distribution
  impact_type: Credential theft, Cryptocurrency theft, Data theft, Remote access
  references:
    - https://thehackernews.com/2024/07/indian-software-firms-products-hacked.html
    - https://www.rapid7.com/blog/post/2024/06/27/supply-chain-compromise-leads-to-trojanized-installers-for-notezilla-recentx-copywhiz/
  historical_artifacts:
    - http://conceptworld.com/NotezillaSetup.exe
    - http://conceptworld.com/NotezillaSetup32.exe
    - http://conceptworld.com/RecentXSetup.exe
    - http://conceptworld.com/RecentXSetup32.exe
    - http://conceptworld.com/CopywhizSetup.exe
    - http://conceptworld.com/CopywhizSetup32.exe
  domain: conceptworld.com
  domain_type: project download host
  artifact_type: binary archive
  hashes:
    - sha256:6F49756749D175058F15D5F3C80C8A7D46E80EC3E5EB9FB31F4346ABDB72A0E7
    - sha256:BFA99C41AECC814DE5B9EB8397A27E516C8B0A4E31EDD9ED1304DA6C996B4AAA
    - sha256:2EAE4F06F2C376C6206C632AC93F4E8C4B3E0E63ECA3118E883F8AC479B2F852
    - sha256:048CAE10558CDDFB2CF0ADE25F1101909BBA58D0A448E0D78590CC5E64E95127
    - sha256:4DF9B7DA9590990230ED2AB9B4C3D399CF770ED7F6C36A8A10285375FD5A292F
    - sha256:EBF2B84ED64629242F8D0ABFCA73344736205249539474E8F57D1D3DBE8CCC41
