- name: KMPlayer
  title: KMPlayer installer/updates distributed malware.
  synopsis: The official KMPlayer, a freeware media player, reportedly distributed unwanted software, adware, or potentially more malicious payloads through its installer or update process in certain versions or distribution channels. Users experienced unexpected software installations and advertisements.
  start_date: 2018-01-01 # Approximate period of increased reports, though bundling issues existed earlier
  end_date: 2018-12-31 # Reports were prominent during this year
  attribution_type: Adware bundlers # Or compromised distribution
  component_type: Application
  lang: Various # Payloads varied
  cause: Bundled software # or compromised distribution
  motive: Financial gain # (Adware)
  transitive: false
  insertion_phase: distribution
  impact_type: Adware, Potentially Unwanted Programs (PUPs)
  references:
    - https://www.ghacks.net/2018/02/05/kmplayer-serves-adware/
    - https://www.reddit.com/r/software/comments/c1x1lz/kmplayer_now_has_malwarecryptominer/
  versions:
    - Various versions around 2018, specific builds often tied to download sources.
  domain: kmplayer.com # Official site, but bundling sometimes occurred via third-party download portals too.
  domain_type: project download host
  artifact_type: binary archive
  historical_artifacts:
    - "KMPlayer installers downloaded from kmplayer.com or various third-party download sites around 2018, reported to bundle adware or PUPs."
  current_artifacts:
    - "https://www.ghacks.net/2018/02/05/kmplayer-serves-adware/" # (Link might be dead, but documents the issue)
    - "https://www.reddit.com/r/software/comments/c1x1lz/kmplayer_now_has_malwarecryptominer/" # User reports of bundled malware/cryptominer
