- name: rest-client
  title: rest-client gem backdoor steals credentials.
  repo: https://github.com/rest-client/rest-client
  synopsis: A maintainer's RubyGems.org account was compromised due to a reused password. Attackers then published malicious versions of the rest-client gem containing a backdoor. This backdoor exfiltrated environment variables and could execute arbitrary remote commands.
  start_date: 2019-08-14
  end_date: 2019-08-19
  attribution_type: Individual hacker
  component_type: Library
  lang: ruby
  cause: Stolen credentials
  motive: Financial gain
  transitive: false
  insertion_phase: distribution
  impact_type: Credential theft, Remote access
  impact_user_count: 2450
  references:
    - https://github.com/rest-client/rest-client/issues/713
    - https://snyk.io/blog/code-execution-back-door-found-in-rubys-rest-client-library/
    - https://www.helpnetsecurity.com/2019/08/21/backdoored-ruby-gems/
  versions:
    - "1.6.10"
    - "1.6.11"
    - "1.6.12"
    - "1.6.13"
  historical_artifacts:
    - https://rubygems.org/gems/rest-client/versions/1.6.10
    - https://rubygems.org/gems/rest-client/versions/1.6.11
    - https://rubygems.org/gems/rest-client/versions/1.6.12
    - https://rubygems.org/gems/rest-client/versions/1.6.13
  current_artifacts:
    - https://snyk.io/blog/code-execution-back-door-found-in-rubys-rest-client-library/ # Analysis with code snippets
    - https://github.com/rest-client/rest-client/issues/713 # GitHub issue with user reports
    - https://github.com/rubysec/ruby-advisory-db/blob/master/gems/rest-client/CVE-2019-15224.yml # Advisory details
  hashes:
    - sha256:9900a959f1ebf2a27e45f5a9ebff2440edc7a91181e4aae2d3c89dd03dca3dfe # rest-client-1.6.10.gem
    - sha256:cca62351eceaebe5ba440a8fc00a3170a58e0af67a755d2bce743c11a2b1437e # rest-client-1.6.13.gem
  domain: rubygems.org
  domain_type: package host
  artifact_type: source archive
